== Preface by John Gough

That biography which describes the lives of such as have
steadily directed their course through this world to a better,
in piety toward God and goodness of heart and life among men, seems,
in an especial manner, to claim our serious and attentive perusal.
Some of these good men, from a view of being helpful and serviceable to mankind,
when they shall be no more in this state of mutability,
have left behind them lively monuments of their experience of
the work of sanctification and saving grace in them;
reciting not only the occurrences of their lives, but the motives of their actions,
and the effect of those occurrences on the state of their minds;
unfolding the gradual operation of the grace of God, for their redemption from evil,
and showing forth the fruits of the spirit, out of a good conduct.
Herein leaving, as it were, the prints of their footsteps to lasting felicity,
for their survivors to trace the path to the like glorious inheritance.

Of this kind of biography, we have had several tracts published in our Society;
and having perused them with much satisfaction and advantage,
and been thereby animated to an ardent desire of treading the same path to blessedness,
I am induced the more readily to forward the publication of the following sheets,
and to recommend them to the solid attention of my friends,
particularly to the youth of this generation.
Reading and study, as well as every other occupation of our lives,
are most properly and profitably employed in the
pursuit and acquisition of those virtuous dispositions,
whereby we may please our Maker, fill up our stations in life with propriety,
and be good examples in our generation, it is a matter of importance to all,
but especially to this age,
to be very careful and well-directed in the choice of the books they read,
as well as the company they familiarly associate with;
that they be such as may make profitable impressions upon them.
These silent companions of the closet, communicate a good or evil influence,
according to the subjects they treat of, and the manner in which they are treated,
and have a secret, but powerful effect upon the tender mind;
and the apostle`'s observation, that, "`evil communications corrupt good manners,`" is,
in my opinion, applicable to corrupting books, as well as to corrupting companions.

From the clear sense they had of the pernicious tendency of such compositions,
our friends, both in a private and collective capacity,
have been frequently concerned to recommend a care in parents and guardians,
to prevent and caution youth and others,
to restrain their inclination to read "`such
books as tend to leaven the mind into vanity,
profaneness and infidelity,`"^
footnote:[See yearly meeting`'s Epistle, 1723, 1762, etc.]
under which description are comprised, "`plays, novels and romances,
and all those which have a tendency to lead the mind from piety,
and to oppose or reject the divine authority of the holy Scriptures.`"
This licentious age, which has produced an inundation of fictitious compositions,
romances and novels in abundance,
presents an occasion to revive the caution to our young friends,
to beware of touching the unclean thing,
lest their minds be imperceptibly defiled thereby.

Such writings being adapted to the depraved
taste of an indolent and luxurious generation,
afford no profitable instruction or real improvement in morals, in understanding,
or in the temper of the mind; and the time employed therein, is in general misspent,
or spent to a bad purpose.
"`There is but little need to drive away that by foolish divertisements,
which flies away so swiftly of itself; and when once gone is never to be recalled.
Plays, balls, treats, romances, music, love-sonnets, and the like,
will be a very invalid plea, for any other purpose than their condemnation,
who are taken and delighted therewith,
at the revelation of the righteous judgment of God.`"
(William Penn`'s _No Cross No Crown,_ chap. 15, sec. 7.)
None, I believe, are better or wiser,
for the hours they pass in perusing such productions.
The greater part, being the invention of corrupt minds, have a very corrupting influence.
And those which appear most plausible,
are too generally formed to fill the head with romantic ideas and airy imaginations;
to flatter our pride, infuse a taste for sensual pleasures,
nourish our propensity to worldly grandeur, and the desire of great possessions,
and to bring the mind into a dissipated state;
operating in a direction opposite to the grace of God, which brings salvation,
and teaches us to deny all ungodliness and worldly lusts; and to live soberly,
righteously, and godly in this present world.

For these reasons I am induced to cast in my mite to this concern,
of the Society I am connected with in religious fellowship,
for the preservation of their members from these hurtful pursuits;
desiring they may receive the word of exhortation to
refrain from unprofitable or prejudicial compositions,
as well as to peruse with seriousness,
such as tend to impress the mind with religious considerations,
and influence it to the practice of piety and virtue.

I have reason to believe it was a practice with the author of the ensuing pages,
to take frequent reviews of his life, keeping an account thereof,
in order to take a more minute retrospection,
and to form a more precise judgment how he was
prepared and preparing for the final account;
a profitable, rational, and religious exercise,
which it might be advantageous for all to employ themselves in, every day of their lives.
At three different periods he commenced a review of the whole, I imagine,
with a more extensive view; but had proceeded only a little way in the last,
when he was removed from this life.
I have traced the last as far as it was carried forward, and the second to the end;
and from that period, having collected what authentic memorials I could,
have in a supplement, continued the narration to the end of his life.

I have also annexed an epistle to friends in Ireland,
which I found among the papers from which the following memoirs are compiled,
which seems designed for publication,
and in which there are many observations well worthy
the attention of those to whom it is addressed,
and of others into whose hands it may fall.
