== Introduction

For my own future benefit, and for theirs too into whose hands it may fall,
I am induced to commit to writing the following review of my days,
now in the sixty-sixth year of my age.
Since we are launched on the ocean of life,
our principal care ought to be to steer our course
through it to the port of rest and unmixed felicity,
though it be through hardship and self-denial; since, if we fail of this at last,
it is then too late to amend it.

Could all the pleasures and advantages of this life,
be attained and enjoyed perfect and unmixed to its close,
they would be no compensation for the loss of happiness in a future and immortal state.
But those pleasures and advantages never can be so enjoyed by any one,
unless his passions and inclinations are subject to the government of God,
who alone ought to govern his creatures,
and who discovers his will to the humble attentive mind.

The temporary enjoyers of the good things of this life,
may show an appearance of pleasure to ignorant spectators, while they seem to float,
without interruption, in the midst of gratifications and amusements;
yet a secret worm is often felt by them,
gnawing at the root of their exaltation and grandeur.

It is the universal regard of Omnipotence,
which rebukes them for letting loose the reins of their lusts or eager inclinations,
designing thereby their timely reformation for their everlasting good.
He often opposes the ambitious and proud in their career with the unwelcome discovery,
that they are engaged in other pursuits than those that heaven designed for them;
not applying their precious time and talents to the
great and good purpose for which they were given.
Sometimes He displays the beauties and benefits of rectitude, deserted by them;
and sometimes the horror and sad consequence of persisting in
the neglect or violation of duty thus discovered,
on the one hand, and counteracted by them on the other.

Hence too generally, disliking the check to present ease and pleasure,
such as are entrusted with the means of doing good, and helping others on their way,
turn their attention from this omnipresent monitor, this faithful bosom friend,
they fly to tempting vanities, to soothing deceptions, to amusing recreations;
they bear their heads aloft among the envying multitudes,
and seek to drown his salutary admonitions in splendor, noise,
intemperance and dissipation.

Many such I have known, who are now gone to their long homes,
whom in my younger years I envied,
I have been so foolish as to transfer my envy from them, after they disappeared,
to their vain and short-lived successors; many of whom are also gone,
and so will it be with the rest before long.
And then what follows to those that have left their heaven behind them;
who assuming to themselves the direction that was due to God,
have refused to reverence and obey his laws?
Ah, then the enviers and the envied, like the blind led by the blind, fall into one abyss.
Unfit for the regions of pure love to God and each other, of perfect peace,
of joy unspeakable and full of glory, they are debarred from admission into them.
Associated with rebellious spirits, their bitterness, envy, resentment,
eager desires ungratified, unceasing vexation and anguish descend with them,
in an unbodied state.

A sensual earthly mind is too much vitiated to relish the pure joys,
or to suit the society of the spirits of the just made perfect.
Goodness is painful to the wicked, being so contrary to the depravity of their nature.
Heaven would be no heaven to them.

A change of heart is necessary to be experienced by every man,
from a state of nature to a state of grace;
from earthly and sensual dispositions and affections, to holy and heavenly,
in order to be fitted for the fruition of, as well as the admission into,
the kingdom of heaven.
It is then the greatest wisdom, while time and opportunity are afforded,
to use all diligence to attain that state of mind in which we may be prepared,
when all the transitory delights, amusements and desirable objects of this world fail,
to be received into everlasting habitations.
Our hearts ought to be filled with thankfulness to God,
who in his universal love to mankind, has provided for them a physician,
able and willing to heal all nations, to create clean hearts,
and renew right spirits in all who submit to him and follow his directions.

But in order to attain this desirable state,
we must make a total surrender of ourselves to the divine will revealed to us,
in daily self-denial and fidelity; persevering therein to the end of our days,
ardent in desire to do good, and to be conformed to the mind of our Creator.

The less we look unnecessarily into the world, or covet its honours, favours,
friendship and greatness, and the more we look to God with a single eye,
and covet his honour, favour, friendship and riches,
the more shall we experience a growth in the very root,
and in all the branches of the divine life,
that we may be as a chaste spouse to Christ in every desire and aim,
in every motion of the mind, and its companion the body too.
Surely he ever merits it from us, even he who has graciously visited,
and from day to day invited, and called us out of the spirit and ways of the world,
to join himself, in order to partake with him and his,
of pure peace and joy in the present life, and infinitely in a future state.
His call is "`come out from among them, and be separate; touch no unclean thing,
and I will receive you, and I will be a father to you,`" etc.

By this call were our honourable predecessors in the beginning,
separated from the spirit and ways of the world,
and incited to refuse touching the unclean thing
or whatever sprang from an impure source,
what persecution soever that refusal might cost them;
knowing that he whom they obeyed and in whom they trusted,
would carry them through all opposition, which they experienced to their unspeakable joy,
to be fulfilled, and many of them testified it to the world, both living and dying.

Those happy men and women,
through their faithful labours with the divine blessing upon them,
left the Lord's vineyard well fenced and clean, having gathered out the stones thereof,
and abounding with the excellent fruits of the holy Spirit of Christ.

After this, degeneracy stole in, a revolting to the world, imbibing its spirit,
resuming its customs, language and manners;
which has since widely spread and overflowed like a deluge, broken down the fence,
and introduced an unhappy change in the state of our society.

Yet there is no change in God or his laws.
O then, that we may speedily return back to him and them,
and to that state from which we have fallen, else great it is to be feared,
will be our condemnation.

Having premised these brief observations, I now proceed to the narrative of my own life.
