== An Epistle to Friends in all parts of Ireland.

Dearly beloved friends, Under a concern for the welfare of our religious Society,
yet left in Ireland, I think it my duty,
"`to stir up the pure mind by way of remembrance.`"

1+++.+++ In the first place, I desire that none under our name may be raw and ignorant,
at a loss, if asked what we profess, or what is our fundamental principle;
but having the heartfelt experience thereof,
"`be ready always,`" as a good apostle advises,
"`to give an answer,`" or a "`reason of the hope that is in you,
with meekness and fear.`"

We profess to be a people called out of the corrupt spirit and customs of the world,
out of all evil words and works, to follow Christ,
in a close and inward adherence to the secret discoveries which he gives us of our duty;
that as his faithful servants, we may enjoy his favour, both while here,
and eternally hereafter.

And our fundamental principle is this, that as God has created us to be forever happy,
he has bestowed his light, grace, or holy Spirit, to fit and prepare us for it.
Hereby he teaches us what to deny, and how to live, to attain this great and glorious end.

If we adhere to this divine gift, we shall love him above all things,
and other gifts and blessings, as we ought to do.
Parents will love their children in the Lord;
children will be an honour to their parents, by a well-guarded and dutiful conduct.
The young and the aged will be joined as brethren, in one good concern.

Thus would a holy harmony be seen and felt, as formerly; and we, in that peace,
order and union, reverencing the Lord our God,
should enjoy the sweet influences of his presence, and the joy of his salvation.

Why are we members of a separate society but to be more closely
connected with the divine source of all purity and goodness,
walking in the light of the Lord, that it might shine in our lives,
as way-marks to neighbours and sober inquirers, that they, being won by our good conduct,
may have cause to bless God on our behalf?
Thus were many convinced of our principles, and drawn into our Society,
even at the hazard or loss of all that was dear to them in the world.

2+++.+++ I think it necessary to enter upon some points more particularly,
and to add such exhortations thereupon, as my present concern may engage me to impart.

"`Submit yourselves to every ordinance of man, for the Lord`'s sake:`" actively,
when not contrary to the law of God; passively, when it is opposite thereto.
This is conformable to the example of Christ and his apostles, as well as of good men,
in former ages, and of all the worthy martyrs in later days.

The Jews complained of Christ for transgressing or breaking their laws; at last,
when Pontius Pilate said repeatedly, "`I find no fault in him,`" they answered,
"`We have a law, and by our law he ought to die.`"

From our fundamental principle, before mentioned, proceeded our well known principles,
or testimony for Christ our Lord, in its various branches,
which it is our incumbent duty to bear, and to show forth to the world;
as in the following instances.

3+++.+++ Our blessed Lord commands us, "`not to swear at all.`"
It is our duty firmly to obey his command, whenever we are tried herein,
and rather to suffer patiently what human laws may inflict,
than to take an oath on any account whatsoever.
Thus Daniel and the three worthy Hebrews,
chose rather to sacrifice their bodies to the lions`' den, and to the fiery furnace,
than to comply with the law of man,
when it demanded a revolt from their duty to their supreme Sovereign.

4+++.+++ The law of man sometimes requires wars and fightings,
and actively to contribute thereto; but Christ commands us to love our enemies,
and do to all men nothing but what is good.
As his professed subjects, we cannot therefore, actively contribute to military affairs.
Our Lord said to Pilate, '`If my kingdom were of this world,
then would my servants fight.`"
Again, whatever injuries or ill usage we receive, we must follow his pattern,
not rendering reviling for reviling, leaving vengeance to the Lord to whom it belongs.
None among us must either fight, or do any violent action, tending to provoke thereto.
We must trust in the Lord,
and then he will discover the best means of helping and healing the evil in others,
or animate us innocently to bear our testimony against it,
where hearts are too hard to admit any offered help.
In this case our Lord assures us, that great is our reward in heaven;
for such usage the righteous who were before us have met with.

5+++.+++ Our dear Lord commands his own ministers freely to give,
as from him they freely receive; and he changes not: a hireling,
manmade ministry therefore, is none of his; nor can we join in supporting it as such.
Though the law of man has established it, we ought to do as the apostles did;
"`And to obey God rather than man.`"
The gospel of Christ is free, not subject to worldly traffic.
It can neither be bought nor sold.
It is the power of God to salvation.
It brings the soul, which receives and submits to it,
into union with the Father of lights, by leavening it into his divine nature.
That which selfish priests purchase and demand money for, is therefore not the gospel;
and their pretending it to be so, is an artful imposition.

This, with many other things of like kind, our ancestors discovered in the true light,
and therefore, like holy Daniel and his brethren,
passively submitted to the laws which required the support of this imposition,
and to the rigorous execution of those laws.
By their courage and constancy herein, they made the way smooth and easy to us,
our sufferings being light in comparison of theirs.
It was nothing but the love of God that animated them
cheerfully to suffer great spoiling of goods,
with long and hard imprisonments;
separated from all that was near and dear to them in the world.
It was in support of their testimony to the universality of God`'s love to mankind,
who invites them that are athirst, and them that have no money,
to come and buy wine and milk, without money and without price.

May their descendants and successors, from generation to generation,
come up after them in the same noble cause.
So would they minister joy to such as have no other interest in view,
but the spiritual health and vigor of the body, and of every member therein.
Some indeed, of late years, have degenerated from that fidelity to God,
which those worthies ever firmly manifested.
These throw down what their forefathers laboured to build up,
and dissolve that spiritual bond, which should unite us in faith and love.
I earnestly desire they would draw near in spirit to Christ, and to his militant church,
to be a help to faithful friends.
When any of you are tried with future demands on such accounts,
I cannot but wish for you, as I look back to the worthies gone,
that like them you may stand fast, in the freedom of the gospel, without flinching,
or any way evading our testimony for it.
I fully believe that your fidelity in such trials,
would be the means of giving you new life and strength for the
zealous and upright discharge of other Christian duties,
and of making you both useful and honourable members, not only of civil,
but also of religious society.

As to that formal worship, which is begun and carried on in the will of man,
our faithful predecessors could have no unity with it,
nor actively contribute to the support of the
places or materials appropriated to such worship.

6+++.+++ On the other hand,
they most conscientiously paid an active obedience to
the laws which enjoin the payment of customs,
duties, and excise, to the king and government; and were zealous,
both by example and precept, to induce all to be careful and punctual therein,
and not on any account to deal in goods suspected to be clandestinely imported,
nor even to buy any of them for their own private consumption.
So should we still keep ourselves entirely clear from this and
every other sort of unrighteous gains or savings.

7+++.+++ The law of the land sets apart one day in seven, for religious retirement,
and the worship of God.
This our forefathers approved of, and religiously observed; though at the same time,
they testified that the Jewish sabbath is ended, by the coming of Christ;
and that there is no inherent holiness in any one day more than another.
I have long had an earnest desire that all our friends would
duly observe and apply that day to its proper purpose,
to begin each week aright, and so to hold on to the end of it;
to avoid as much as possible, travelling about worldly affairs on that day,
and be constant, while in health, in attending meetings for worship.
Deny yourselves the liberty of walking abroad, at such time, or in such manner,
as will not be of good example to the idle multitude,
who give a loose rein to licentious inclinations, on that day.
Rather choose to have your families collected for reading the holy Scriptures,
or what may make good impressions on their minds, that when it shall be said,
"`Give an account of your stewardship,
for you may be no longer steward,`" we then may be ready to give our accounts with joy,
and receive the answer of, "`Well done, good and faithful servant.
Enter into the joy of your Lord.`"

8+++.+++ For lack of this care, what harms abound!
I am reluctant to mention them,
but hope you will bear with me when you duly consider that nothing but well wishing love,
induces me to lay them before you,
in order that all might join in contributing a timely remedy thereto,
with the means of doing it, which the Lord furnishes us with.

It is apparent, that from hence the love of God in many waxes cold.
How they make light of religious duties!
What a slender attendance of week-day meetings for the worship of God,
as well as of those which are held for a united care of the good of the body;
so that it may now be said of many, as in sorrowful days formerly,
"`The ways of Zion mourn, because none come to her solemn feasts.`"
Again, what restlessness in meetings, what outward indications of spiritual indolence,
of absent and wandering minds, of neglect of the awful duty of worship,
due from us to our great Creator; what gazing about, or falling asleep.
O, it is grievous, and tends to give strangers a dishonourable idea concerning us,
while we profess the pure spiritual worship of God, according to his own institution;
and while our dear Saviour has assured us,
that where two or three are gathered together in his name, he is in the midst of them.
Again, from hence, what violations of our Christian testimony in its sundry branches;
what weakness and inconsistency in conduct with that divine principle, which we profess!
How do many trample upon the precious labours and sufferings of men,
whose memories are and ever will be blessed, as they were valiant for the truth,
revealed to them by Christ their dearest Lord?
And shall we not be brought to account for these things?
Will not our account be heavier in the reckoning day, than that of others,
who have not been favoured in so high a degree, nor so much striven with,
by the spirit of the Lord, who declared to the old world, before its final ruin,
"`My spirit shall not always strive with man.`"

9+++.+++ Again, how many in these perilous days run back, and draw others with them,
into the vanities of the times, into a conformity with the world,
both in dress and address, into the company of such as indulge the same dispositions,
till the plain, honest manners of sincere and affectionate friends,
are falling into disuse, being such as some are ashamed of.
Thus were many ashamed of Christ, and offended in him,
for his plain and humble appearance, when in the body;
but he declared that he also would be ashamed of them, or would deny them,
before his Father and his holy angels.

From these pernicious liberties, have proceeded mixed marriages,
running out to the priests, confusion in families, affliction and anguish of parents,
in the bad returns made to them by disobedient children,
painful wounds to our Christian Society.
Many, by these traps and snares of the common enemy,
have been carried away into the wide world;
and quite lost as to the dedication of their hearts and lives,
to the love and fear of God; and but few have stood in the gap,
to prevent their thus running out; few have joined in repairing the breaches,
made by backsliders, in that wall of defence which the Lord, by his power and Spirit,
had erected about us.

In this general decline of the Society,
there seems to be great cause to fear the further spreading of these harms,
unless the Lord in mercy, turn the hearts of many timely to himself,
which we ardently pray for, knowing that, except the Lord build the house,
men labour but in vain; yet we must do our duty;
otherwise we shall not be clear in his sight; and he orders now, as he did formerly,
line upon line, and precept upon precept, in order that all may be timely warned,
whether they will hear or forbear.

I believe there are none joined in profession with us,
who deviate from our principle of self-denial, and plainness in habit and speech,
who have not been secretly shown that it is wrong,
that it is a compliance with the spirit of the world, a refusal of the cross of Christ,
a denial of him before men.
But they listen to that voice which beguiled Eve,
which tells them that there is no harm in such deviations,
or that they are small matters;
though it is manifest that such small matters
have opened the door gradually wider and wider,
to the gross declension which has overspread.
Though many are deceived and darkened by the enemy, to deem them small matters,
yet they have great consequences, as they tend to debar us of future happiness,
and to center us in justly deserved punishments, for disobeying and disregarding Christ,
who leads into humility and plainness,
and preferring that enemy who seduces into pride and worldly conformity.

I often look with pity, on the victims to the vanities of the world,
who sell their birthright for a mess of pottage;
often desiring that they may quit the pursuit of shadows, wisely to seek,
and happily possess the most inestimable and enduring substance.
Hereby they would give solid joy to their well wishing friends,
and gain an ample share thereof in themselves; a joy not like the pleasures of sin,
which are but for a season, and are followed with a certain and severe sting;
a joy which will go beyond the grave, to receive an infinite increase,
and an endless duration.

10+++.+++ In regard to such as have not yet much departed from that plainness,
at least in dress, in which they were educated;
some probably may not be under any strong temptation,
to run into the foolish fashions of a corrupt age.
Yet the enemy seeks to catch them in some other snares;
and perhaps some of these may be as ignorant,
and as void of experience of the divine principle we profess,
as some of the more fashionable.
Outward plainness, without inward humility, mercy, justice and charity,
is of very little worth.
Except we follow after these virtues, obvious faults in temper and conduct will appear,
to discover our emptiness, and to serve some for an argument against plainness,
or for a subject of ridicule; and do more harm to the cause of truth,
than greater errors in the conduct of open and professed libertines.

How grievously disappointing are they who carry a right appearance,
yet when tried are found to be insipid and dead, as to the life of righteousness.
Wherefore, let none value themselves on a plain outside,
as if that of itself were sufficient.
It is as far from it as the state of those formerly complained of,
who drew nigh to the Lord with their mouths, and with their lips honoured him,
but their hearts were far from him.

Be not deceived; God is not mocked by fair appearances, or empty pretences;
but such as every man sows, he must reap.
If under the best appearance, or strictest form, we sow to the flesh,
we shall only reap corruption, and the miserable fruits of hypocrisy,
professing one thing and practising another; when they who have sowed to the spirit,
shall reap the happy fruits of their fidelity to God.

If we look over our Society in this nation, and take a view,
both of those who are plain in dress, and those who are otherwise,
how many of both sorts have their minds fast rooted in this present world,
devoting all their talents to it, rejecting the counsel of Christ,
who directs us "`to seek first the kingdom of
God,`" or to live and act under his government.
Hence in some places, what poor, lifeless meetings!
How little of the sacred fire of divine love burning!
How little of the light of the glory of God shining!
No living minister left among them, and scarce one living member of the body of Christ,
to feel for the others, and take some tender care of them for their good;
their lamps gone out,
and scarcely any oil retained in a single vessel a week-day meeting hardly kept up,
and the one meeting on the first-day badly attended.
Thus have some meetings died away, and are lost; and others appear to be in a languid,
sickly condition, seeming scarce likely to live long,
except they timely apply to the great and good Physician,
who is both able and willing to restore life, health, soundness and vigor,
to raise up and qualify "`Judges, as at the first, and counsellors,
as at the beginning.`"
But formerly, when in the body, in some places he did none of his mighty works,
by reason of their unbelief; so now, when his ministers visit such places,
they find the gospel has not a free course;
they can at best but feebly labour in such hard spots.
The word preached does not profit, by reason of not meeting with faith in them that hear.

Great is the mystery of iniquity, in which the subtle serpent works in many,
to their hurt or ruin, unawares to them,
for lack of their paying due regard and attention, to that grace of God,
which would discover the hidden snare, and preserve from it.
Hence a wrong spirit usurps the government due to God, and gradually hardens the heart,
till the salvation of the immortal soul becomes a matter of very little
concern--the first and great commandment of loving God with the whole heart,
being much violated.
Such are in a most dangerous state, except they turn in haste,
"`to flee from the wrath that is to come.`"
I often earnestly desire, that you who are of this kind, would do it,
lest you be left to your own courses in that broad way, which leads to destruction,
and "`the things which belong to your peace, be hid from your eyes.`"

11+++.+++ "`The Lord has showed unto you, O man, what is good.`"
But many have allowed the good impressions they have been favoured with,
to be like the morning dew, which soon passes away.
They rush into irreligious company and self-indulging liberties, which,
like the fowls of the air, carry off all the good seed of the kingdom,
which infinite Goodness had sowed in their minds.

What need have we then, to prize and pursue Christ`'s counsel,
"`to watch and pray,`" not to enter into these temptations;
to abstain from all appearance of evil, to avoid such company as deadly poison,
as there can be no fellowship between light and darkness, or between Christ and Belial;
and we naturally become like those whom we love, and with whom we associate.

Never go to places of public diversion, such as play houses, horse races, cock fightings,
or to ale houses, those haunts of the licentious, who fear not God.
Be watchful, and clear from intemperance.
Live as men accountable to God, your hearts and your citizenship being in heaven,
and your moderation appearing in all things.

All would be glad to escape everlasting misery,
the habitation of rebels to the laws and government of our great Creator.
All would be glad to be admitted into everlasting happiness,
the portion of such as obey those laws and that government.
Why then will any among us,
be the enemy`'s instruments in promoting apostacy from
the very life of true religion and godliness?
Oh, rather choose to escape misery and ensure happiness.
Break off all connections which are obstacles to it.
It is Christ`'s command, "`If your right hand offend, cut it off.`"
Lay aside every weight, and the sin which most easily besets.
Be obedient to him, and you will be happy,
separated from the miserable regions of obstinate and obdurate sinners.

12+++.+++ Let us call to mind, and not hastily forget it, that Christ has given himself for us,
"`to redeem us from all iniquity, and purify unto himself a peculiar people,
zealous of good works.`"
Yet, notwithstanding all this, it is evident that too many among us are induced,
and induce one another, to slight the kindest offers of their best friend.
They give ear to the voice of the stranger, and swayed by his persuasions,
put off their embracing a Saviour`'s offer.
Far from being zealous of doing all that is well pleasing to God,
they counteract that profession, to which he, by his holy Spirit, has called us.
To propose to obey the Almighty at some future day, and in that presumptuous hope,
to stifle divine conviction, is a most fatal artifice of the grand adversary,
whereby he insensibly darkens the mind, and hardens the heart, to render us his vassals,
and to secure us to himself as such.
As delays herein are infinitely dangerous--as we cannot repent when we will,
for repentance is God`'s gift--begin then, while it is the day of God`'s visitation;
for when the night overtakes, none can work out their soul`'s salvation.

13+++.+++ Wherefore, cleave close in heart to the divine gift, the mystery hid from ages,
but now revealed, even Christ in you, the hope of glory,
that your souls may be enamoured with that beauty which will never fade.
Lay hold of all the helps and means by him provided.
Be kind to all, but familiar with few, and those few such as fear the Lord.
This fear preserved Joseph in the time of trial;
but for lack of it Absalom overset all his personal advantages.
Seek to be closely linked with good friends;
for "`two are better than one,`" "`and a three-fold cord is not easily broken.`"
Great are the benefits and solid satisfactions found in truly religious society.
Formerly when the proud were counted happy, they who feared the Lord,
spoke often one to another,
and the Lord declared his approbation of the pious
ardour with which they mutually animated each other.
As on one hand, "`the friendship of the world is enmity with God;`" so on the other,
Israel, the Lord`'s people, were to dwell alone, and not to be numbered with the nations.
Their safety and true peace depending hereupon,
they were enjoined not to contract any alliance or intimacy with them,
to prevent the decay of that fervent love to the Lord their God,
which he inspired them with, while they abode in his covenant,
and duly observed his laws, his statutes and ordinances;
and to prevent their children from contracting the manners of those nations,
and running into their fashions and customs.
While they kept together in a united care and veneration of the Lord,
they prospered both outwardly and inwardly; nothing could harm them,
no effort of the common enemy could prevail against them.
May we thus keep together, strengthening one another in the love of God,
and in faithfulness to him, and then we may be sure that our case will be the very same.

14+++.+++ There are many, we believe, orderly and reputable in their lives,
who need to be more baptized into the ardent love of God,
and dedication of heart to his cause, that they may not be like slothful servants,
at ease in Zion, and indulging themselves, instead of serving the Lord.
The harvest is great,
and needs more labourers to fill up the vacant
places of many removed from works to rewards.
What lack of ministers, elders, of such whom the Holy Ghost has made overseers,
taking heed to themselves and to the flock,
of helpers of one another in animating visits, both to families and individuals,
in the lively flow of that love which the Lord gives to
them who devote their hearts to his service.

A few yet are mercifully preserved, who, for Zion`'s sake, cannot be at ease,
but through all discouragements hold on their way, knowing they serve a good master,
and resolving through his grace, never to desert his service,
but to keep their places under his direction,
and to hold fast the blessed truth in the love of it, to the end of their lives.
May he grant an increase of their number and strength;
I desire above all things for myself, that to the end of my days,
I may be one of their number.
O my soul, come into their secret adoration of God; with their assembly herein,
may you ever be united;
for indeed the Lord is good to them that seek and diligently serve him,
nourishing that life which is hid with Christ, a life which will never die;
well rewarding them for all their labours,
and for the sacrifices which they offer to him on the altar of obedience,
giving them a hundred-fold.

15+++.+++ When our Lord told his disciples that one of them should betray him,
the rest heard it with concern, and inquired,
"`Is it I?`" Many have contributed to the great declension,
and each of us should inquire.
Is it I? Many have need to be created anew in Christ Jesus, unto good works;
but they must first put off the old man, with his deeds,
in deep humiliation before the Lord;
which to them who patiently abide under his righteous judgments for sin,
draws down the gift of repentance unto salvation, never to be repented of;
and that new birth, without which we can have no place in his kingdom.
We must give up all our idols, else we are undone.
Our own wills must be subjected to the will of God.
All our own wisdom must be laid at his feet.
We must deny ourselves, take up our cross daily and follow him.
There are no other terms on which life everlasting is to be had.
Our Lord informs us, that they who expect to gain it by climbing up any other way,
will be treated as thieves and robbers.
Oh then, my dear friends, in every part of Ireland,
I earnestly desire that you may buy the truth, whatever it cost you, and sell it not.
Look upon all things beside but as dross or dung in comparison of it.
Let us hold fast the one thing needful, whatever else leaves us, or be taken from us.
So shall we have lived not in vain,
obtaining the great end for which we had a being given us.

16+++.+++ O you parents who have many children, and not much of the world for them,
do not be over anxious on that account,
or make it an excuse for non-attendance of religious duties.
Consider that it may be wisely so ordered, as the means of their preservation;
and if they follow Christ,
it may prove of great advantage to them beyond what you and they are aware of.
A little satisfies a humble mind, as we brought nothing into the world,
and can carry nothing out.
They who obtain the favour of God will neither lack anything needful,
nor covet anything superfluous, but having food and raiment, will therewith be content.
Wherefore be anxious for them only on this account,
that they may lay hold on eternal life, and keep their hold of that;
then they will be truly happy, but not without it, if they had ever so much in the world.
They are indeed justly to be esteemed, who, having more, are thereby the more humbled,
and more abounding in useful services and good works.

And O you young people,
often consider that you are born into the world to be happy forever,
on the terms laid down by Christ, as above mentioned.
With all your gettings, get the favour of the Most High, who invites you to it:
before honour, even true honour with God, is humility; but pride goes before destruction.
You need not envy any one, however great in the world, if you have the Lord on your side.
United with your dear parents in walking humbly with him,
you will have an enlarged view of your happy portion.
Your fervent gratitude, obedience, vigilance and firmness,
will be crowned with the endearing pledges and encouraging foretastes of endless bliss.
So will you be well satisfied with your lots in every condition,
and find that godliness coupled with divine contentment
is the greatest and infinitely the most valuable gain,
being fitted by your blessed Redeemer for life, death, judgment,
and for that eternal joy, which is unspeakable and full of glory.

So will you be alive to God, and of that number whom he pronounces blessed,
who hunger and thirst after righteousness.
So will you carefully watch against everything that is wrong,
both in yourselves and others, and endeavour to stop it in its first beginning;
you will love that which is good, and employ all your talents, with divine help,
to promote it both by example and brotherly counsel.

Then would meetings both for worship and discipline be well attended;
for coming to them under the preparation of heart which is of the Lord,
we should by him be overshadowed with his power and love;
the Sun of righteousness would overspread us,
who illuminates the spiritual mind to discern its duties, and animates to discharge them,
therein to share the good things which God has in store for them that love him.
We should hereby be edified and built up together in the most holy faith,
and concerned to live in reverent love and subjection to him out of meetings,
faithfully maintaining our testimony for Christ, our holy head, in all its branches.

So should we be again, as formerly, a people of one heart and mind,
baptized by one spirit into one body.
All the darkness of ignorance and inexperience,
all the coldness of the worldly or carnal mind would be removed;
and Zion`'s light would yet again go forth with brightness,
and the salvation of God be felt among us as a lamp that burns.

With strong desires on the behalf of all who, in this nation,
join in the profession of the blessed truth,
that they may thus experience the possession of it,
and be partakers of its saving efficacy and lasting peace,
I remain your affectionate and well-wishing friend,

[.signed-section-signature]
James Gough
