== Memoir of James Gough.

I was born at Kendal, in Westmoreland, on the 27th of twelfth month, 1712,
and my parents, John and Mary Gough,
professing the truth as held by the people called Quakers,
I received my education in the same profession.

My mother, who was an industrious, careful, well-minded woman, taught me to read;
and when I was a little turned of five years of age,
I commenced a scholar in friends`' school in my native town,
under the tuition of Thomas Rebanks, at which school I continued till my fifteenth year.
Having a good genius, and a propensity to learning,
I attained with facility and readiness, the Latin and Greek languages;
and my quick proficiency therein,--I being of
little stature for my age,--excited admiration,
procured me the fame of a great scholar, vastly magnified my little stock of attainments;
and also introduced me to the notice of several persons of eminence in the town,
who would frequently question me in respect to my learning,
and were generally pleased with my ready answers.

In particular, a distinguished justice of peace, with his wife,
took a singular notice of me, admitting me, young as I was,
to free conversation with them, and introducing me, at times,
into grand company which frequented their house.
The said justice would say, that if my parents would give me up to him,
he would send me to the university to receive a proper education.
This flattered my ambition, as it was what at that time I heartily wished for.

By these means the seeds of wild nature, the noxious weeds of pride and vain conceit,
the produce of every soil, received strength and nourishment in my early minority,
and shot up high for my childish age.

But in some sort to counterbalance these incentives to pride and airy notions,
I had the advantage of receiving my education in a place,
in and about which there lived many worthy friends,
whose exemplary lives and religious care and labours, often in my early years,
made good impressions on my mind, which, though my own propensities soon effaced them,
left fixed upon my breast an honourable esteem for those truly good men and women,
with painful reflections under the sense of my own infidelity,
and secret wishes for that happy condition,
which I really believed them to be established in,
by Christ their Redeemer and Sovereign.

My understanding was enlightened when very young,
to see both my own deficiencies in duty, and those of many others more advanced in years;
and I thought, if I lived to be a man, their harms should be my warnings.

I remember a worthy minister, Joseph Jordan from Virginia,
having had the small-pox at a friend`'s house in Kendal, and being raised up again;
at the first meeting which he got to after it,
was drawn out in such a moving manner in his ministry,
that the meeting in general seemed to be impressed with great tenderness under it;
and I then, though but very young, had a share therein.
The desirableness of living so as to obtain divine favour,
seemed to be very clearly and strongly set before our view.
And the opportunity had some good effect upon my mind for a short season.

Here we may remark the advantage that accrues to religious society, and to meetings,
where they are favoured with a number of faithful elders, living ministers,
and spiritually minded friends; men of truth, "`fearing God and hating covetousness.`"
The liveliness of their spirits; the clearness of their sight,
and the uniformity of their conduct and conversation,
qualify them to show the people how they should walk in the pursuit of peace,
both by precept and example; precepts drawn from the living spring of experience,
and examples formed by a watchful attention to the pointings and limitations of truth.
I remember some whose very countenances seemed to command awe,
and impress observers with serious consideration; as the salt of the earth,
seasoning those amongst whom they walked,
with a sense of the truth which lived and predominated in them;
under the powerful influence thereof,
these kept up meetings both for worship and discipline,
and were enabled thereby to keep things in good order,
as themselves were a good savour in their allotments.
On the other hand,
we may observe that where the elders and active friends are not under this qualification;
but under the form, are suffering their hearts to go after their covetousness,
secretly departing from under the influence of this divine principle,
the cause and prevalence of truth too often decline
amongst the different ranks of the people,
"`as in the day when a standard-bearer fainteth.`"

My mother made it her maxim in her plan of education,
to accustom her children to useful employment, frugal fare,
and to have our wills crossed,
in order hereby to render us better fitted to undergo any future hardships in life,
that might be allotted to us.
And I have reason to think that her care and endeavours,
with the examples and labours of good friends,
were to me as "`bread cast upon the waters,`" which appeared after many days.
In the intervals of school hours,
she would be for employing me in one useful occupation or other.
This I thought a great hardship; and being much mortified thereby,
I exerted my wits to evade it, often feigning pretences of school-tasks and exercises,
set me by my master, and such like groundless excuses.

The great duty of education, to discharge it rightly,
needs divine instruction and assistance, as much as any duty in life,
and therefore parents have need fervently to pray for it,
and faithfully to follow it when received.
Otherwise they may be in danger of falling short,
and the deviations and miscarriages of the children, at least in part,
may lie at their doors.

But if my mother might seem to err on the one hand, viz: that of severity,
it is to be feared that the far greater number err on the other hand,
that of indulgence and connivance;
and that though the former be more painful for the present,
yet the latter generally proves more pernicious in its effects and future consequences.
I verily believe, I have enjoyed a better state of health,
from being brought up in a hardy way, as my constitution was but weak and tender.

Upon a review of my state at this age,
my recollection represents it as a complication of ambition, envy, craft and deceit;
but even then, a divine monitor was near me,
to manifest and reprove the corruption of my heart and the evil of my ways.
I was sensible of my mother`'s anxious care for my preservation from evil,
and attainment of good; but I eluded as much as I could,
the confinement which she thought conducive thereto, in keeping me under her own eye,
and out of the way of corrupting company.
I loved liberty; I sought it with eagerness, frequently got it by craft,
and abused it to my hurt, as inexperienced young people are apt to do.

In this state, I well remember, I was afraid and ashamed to meet with good friends,
such as I loved and honoured,
being inwardly convicted from the consciousness of my own vile and unguarded conduct.
Sometimes I received from some of them the reproof I deserved;
and sometimes I thought their very silence rebuked me.
At other times in their company,
the love and desire of goodness revived with a strong force;
but being withdrawn therefrom, yielding to temptation,
often reinstated vice in its wonted seat in my heart, and in the direction of my conduct.

I easily and clearly saw the wide difference between good and bad company,
and how much the former was preferable; yet the powerful allurements of the latter,
forcibly drew me into, and held me fast in a wretched captivity thereto,
manifestly contrary to my better judgment, which I fear is the case of many others.

There being a large body of friends in the county of Westmoreland and the adjacent parts,
many of our general meetings were very largely attended;
and as it was the care of the elders,
and other friends concerned for the welfare of the youth,
to encourage them very early to attend the meetings of discipline,
for their improvement in virtue and sobriety; I attended many of these large meetings,
but too frequently without reaping any share of the real benefit intended by them,
or receiving any other impressions than those of vanity and airy ambition;
so that however such meetings were favoured with divine virtue and power,
the dissipation and absence of my foolish, roving mind,
rendered it like the barren heath, not profiting by the fruitful shower,
or cheering beams of the sun.

There is reason to fear that this may be the case of too many young people,
who are pleased to go to these large meetings from other motives than those of piety,
and forgetful of the intent and design of them,
indulge their corrupt inclinations in very unseasonable gaiety and festivity.
What the faithful labourers in the church endeavour to build up,
these in their unguarded conduct pull down,
and sometimes bring reproach and disagreeable reflections on their religious profession.

Had these meetings been constantly beautified
with a uniformity in the conduct of professors,
consistent with the divine principle of truth
and the doctrines of its faithful ministers,
they would have proved of much greater service.
For as the truth is in itself unspotted, and its excellency unchangeable,
the glory and dignity thereof would have shined forth very
amiably and attractively in the eyes of the nations,
had not the misconduct of its professors frequently and
extensively eclipsed its genuine lustre;
which merits the solid consideration of all, who have been educated,
or have joined in profession with us; both when they attend such meetings,
and at all other times.

1727.--Being arrived at my fifteenth year.
my mother was anxious to have me put to some business.
Through her persuasion, my father, in the course of his travels, spoke to David Hall,
the memoirs of whose life are extant, and for whom my mother had an honourable esteem,
and agreed with him to take me as usher to his school,
desiring no other terms for me but my board,
and such instruction as he might see I yet needed;
which gave my mother great satisfaction.

She accompanied me to his house at Skipton in Yorkshire.
Here I experienced the advantage of the education she had given me,
for thereby I was prepared to submit more willingly to continual employ and hardship.
And though many of the boys coming from full houses and plentiful tables,
thought their fare here mean,
as indeed the price for both boarding and tuition was but eight pounds per annum,
yet to me it was in general otherwise.

There happened to be in the family at this time two youths,
whose cases or events in life, I think not improper to mention, by way of caution;
but their names I would wish to be buried in oblivion,
unless they may yet be favoured with repentance to salvation.

The one was a lodger in the house.
He was a valuable pattern and very helpful in the family.
I esteemed him to be in a happy condition, and still believe he was so at that time.
He had a few words in the ministry, and grew in his gift;
but afterwards becoming exalted, and too fond of applause,
he fell into the snares of the grand enemy, and brought a reproach on the truth,
and on the ministry.
What need hath he that standeth, or thinketh he standeth, to take heed lest he fall!

The other was at that time an apprentice to David Hall.
He was afterwards a minister, well esteemed among many friends;
but alas! he also shamefully fell.
And what renders the case of these my formerly well-beloved friends,
still more melancholy, is, that though there is balm in Gilead, yet they and others,
whom the enemy has thus wounded and poisoned, will not turn to the physician there,
but rather endeavour to have their wounds deceitfully healed.

I remember to have heard one, who had basely fallen in an unguarded hour,
boasting a few years after, that he had been washed in the bottom of Jordan,
and had brought up stones of memorial; and this in an affected ministerial way,
when it appeared not to be the case to any but himself;
but rather that the poor man was still under the deception of the crafty enemy,
willing to deceive himself, and wanting to deceive others,
while he was at best but very superficially, washed from deep defilements.
Judgment had not had its perfect work, though he was very willing to think,
and to have it thought by others, that it had; and to evade that awful consideration,
that the most pure and righteous God is jealous of his honour,
and requires our going clean through all that humiliation, labour and patience,
which his light in the conscience discovers to be
necessary for repairing the dishonour incurred.
All palliations or softening excuses; all arts to conciliate human compassion and favour,
are but like fig-leaf coverings,
through which the nakedness of transgressors is
manifest to such as are endued with true sight,
and like daubing over destructive breaches with
untempered mortar.--But enough of this digression,
wishing it may prove useful where needed.

1728+++.+++ When I had stayed in my service at Skipton a little more than a year,
my master gave me leave to return to Kendal to see my relations.
He made me the bearer also of a letter to my father, wherein he signified,
that considering my years, he approved of my qualifications and conduct,
and offered wages for my future service.
My mother took little notice of the offer;
but was exceedingly rejoiced at the other part of the letter,
as giving her better hopes on my behalf than she hitherto had.

In the course of the succeeding year, by agreement between my father and my master,
I spent three months with Richard Kennedy, writing master in Liverpool,
to improve myself in writing, and learn some branches of the mathematics.
One seventh-day while here,
having always a great propensity to see towns and places that were new to me,
I went to see the city of Chester, and lodged two nights at Peter Leadbetter`'s;
in my return by Eastham ferry, which is five miles across to Liverpool,
an elderly gentlewoman having got some play-books in the boat, I offered to read for her:
as I was reading, some horses in the boat grew unruly, which terrified her very much;
so that she put by her play-books, and while we were in the boat,
would no more touch them herself, or suffer me to touch one of them.

Many remarkable preservations I had in my younger days;
but the most remarkable was during my residence at Liverpool, which happened as follows.
One first-day, in the afternoon, I went with some other boys a boating in the dock,
which, by means of flood-gates, was kept so full of water as to keep the ships afloat,
when the tide was out.

We rowed several times from one end of the dock to the other.
At length some rude boys, that were stronger than we, took from us our oar, or oars,
and this in all probability proved the means of our preservation.
For now we found ourselves obliged to work our way with
our hands by the ships to the upper end of the dock.
Just as we reached it, we heard a noise as of the loudest thunder:
climbing up from the boat unto the quay, we soon found that the dock gates,
being grown old were broken down.
The water rushing out in a rapid torrent, bore down all before it,
oversetting and greatly damaging several vessels that lay near.
The frightful nearness of such a danger, and narrow escape from it so affected my mind,
as to invade my sleep that night,
and repeat itself again to my imagination with aggravations of horror.

At the expiration of my three months here, I went to Kendal yearly meeting,
where my father, being just arrived from a journey,
in which he had made his way through Skipton,
informed me that he had agreed with David Hall to bind me to him for four years longer;
this was no agreeable intelligence to me, for although I honoured my worthy master,
yet everything else was not as I could wish it.

I thought I could foresee much hardship to be unavoidably my lot;
yet as my father had so agreed, I thought it my duty to comply.
I endeavoured to put a good heart and face upon it, and so entered upon my part.
During these four years my master was frequently abroad at meetings.
He did not often miss the quarterly meetings at York,
and sometimes attended the yearly meeting at London,
and then the care of the scholars in and out of school lay heavy on me.

Both before my coming to Skipton, and while I was there,
I often had fresh desires kindled in my heart after redemption.
I was clearly shown the necessity of it,
and the danger of delays in a matter of such consequence;
so that I left off playing for a time,
thinking it great infatuation to squander my precious hours in play,
when in danger of my life, and that too forever.
But the most particular reach I had, was at a meeting in our school-house,
under the baptizing ministry of John Fothergill,
whereby I was awakened to vigilance for a season, rising early,
and carefully attending to every step in my business, and the duties of my station.
But soon, the fervour of this sacred flame abated, and I gradually fell back,
and became just what I was before;
yet I did not forget or wholly lose the sense of this day of my visitation;
but often privately lamented my revolt,
and I continued still to maintain a good character amongst friends.

I do not remember much more than what I have
already intimated in general of these four years,
save that one time, when my master was abroad,
I thought myself hardly and unreasonably used,
and thereupon conceived a design to run away by night, it being moon light;
but that kind Providence whose fatherly care was over me,
when I was too little careful for my own well-doing, withheld me.
When the time proposed for putting my design in execution arrived,
the pernicious consequences of such a procedure, were so clearly manifested to my mind,
that I was discouraged from the attempt;
and therefore concluded patiently to endure what might be permitted to befall me,
till the termination of the time contracted for,
might bring me my release in a reputable and conscientious way.

Near the expiration of my time I wrote to some of my friends, acquainting them,
that I intended to try some new place,
and received a letter from my good friend John Wilson of Kendal,
signifying that Alexander Arscott of Bristol wanted an usher,
and offered twenty pounds per annum.
Which offer I readily embraced.

1733.--Leaving Skipton, and the yearly meeting at Kendal approaching, I went thither,
stayed a few days with my mother, and then set forward for Bristol.
In my way at Wolverhampton, standing at the door of the inn where I alighted,
I saw a crowd of people passing by, and heard it was a Quaker`'s funeral;
whereupon I went to it, and our friend Joshua Toft,
whom I do not remember to have seen before, attended it,
and was raised up in a large and living testimony, whereby I was afresh reached,
and considerably tendered, and thence proceeded on my way,
under renewed impressions of good upon my mind, to Worcester.
There I met with William Beesley going to Bristol yearly meeting,
with whom I went in company to Gloucester,
but my horse being tired I was forced to leave him behind,
and walk the greatest part of the remainder of the way in my boots.
In a few weeks after, that worthy minister and elder, John Richardson, of Yorkshire,
landed in company with Robert Jordan from Pennsylvania,
who bought my horse for the same price it cost me.

My good master Alexander Arscott, was like a kind and tender father to me.
He was the eldest son of the parson of Southmolton in Devonshire,
and himself educated at the university of Oxford,
with intention to fit him for the same function.
But when he was just ripe for preferment, and might have had a fair prospect that way,
his father being well beloved and respected among the great men in that country,
he turned his back on all prospects of this kind, being convinced of the blessed truth.
This was a great mortification to his father and mother,
who would both sit weeping by him in the bitterness of their hearts,
as I have heard him relate.
This, he added, pierced him deeply,
as he sincerely desired to be a dutiful son to tender and indulgent parents.

A cloud came over his understanding,
and the enemy in his own breast suggested that he was acting quite wrong.
But as he humbled himself before the Most High, imploring his direction,
he received a fresh sight that he must forsake father and mother for Christ,
and be faithful to the manifestation of his will, through all events.
His parents became afterwards better reconciled to his change,
when he was settled in good business in Bristol,
where he kept a school for the children of friends and others,
from that time till his decease, being about thirty-five years,
and proved helpful to the rest of his father`'s family, in procuring them by his interest,
places for getting a livelihood.

I came up to Bristol quite plain in my garb,
as David Hall would not suffer any other in his family;
and it being the time of the yearly meeting,
at a friend`'s house I fell in company with some well-minded friends,
one or more of whom observed to me,
that sundry young people had come up in the same way
from the north of England to the southern parts,
particularly to London and Bristol;
and after being there a while they ran into the fashions of those places,
till they even outstripped the native inhabitants.

I had not only been educated in plainness,
but also been inwardly convinced of the foundation on which it stood;
and upon hearing this account of the ridiculous
folly and instability of my country folks,
I was sorry that they had given occasion of such remarks to their dishonour,
and took up a resolution to continue steady in my old plain way.
I do not know that I suffered any external disadvantage by it; but if I had,
the cause of truth is worth suffering for,
and the Almighty rewards patient suffering in a good cause.
But I found that good friends seemed to love me the more on this account;
and even others, who were conscious of their degeneracy seemed to respect me,
as apprehending me to be better than themselves;
and I had most peace of mind in continuing in my wonted plainness,
though I was like a speckled bird,
there being even then very few plain-dressed
young people or others in the meeting of Bristol.
I have observed that deviating from this path of plainness, which Truth leads into,
and making departures in dress,
opens the way to intimate connection with young people out of our Society,
or libertines in it;
and so leads further and further from a due
subjection to Christ`'s kingdom and government,
often making them forget and lose the good which they formerly professed,
and consequently draws them along into the utmost danger.
Whereas adhering to the truth and its plain path,
opens the way for safer and more profitable and edifying connections,
as I often found here, to my solid inward satisfaction,
which I hope I shall never forget.

I was now removed far from all my connections, my parents,
relations and the place of my nativity; and was here as a stranger in a strange land,
having at first little or no acquaintance in my new residence.
In this solitary situation, it pleased divine Goodness to take notice of me,
and to favour me afresh with a merciful and reaching visitation of his love to my soul,
and more clearly to reveal his Son in me, whereby I was given plainly to see,
that my safety here and happiness hereafter,
depended upon my yielding faithful obedience to his requirings,
as manifested by his light in my heart;
and that his requirings would be only what tended to my real good and lasting welfare.

This was a day of my soul`'s espousal to Christ Jesus.
I was overcome with his love,
and with admiration of his condescending goodness to such an unworthy creature.
It being the day of the Lord`'s power,
I was ready and willing to do any thing that I saw I ought to do.

Having a strong inclination to poetry,
I had sometimes at Skipton indulged my fancy therein.
But now when the Lord`'s power took hold of me,
I sacrificed all my idols and burned all my collection of poems,
even though some of them were on what would be called good subjects;
for they had too much attracted my mind, and engrossed my thoughts.
I was made sensible that these poems were not my proper business,
that they took the place of what was really so, and therefore I gave them up.
I now saw that I must shut out and leave behind
me what others generally crave and pursue,
viz: the vain desires and delights, which lead away the mind from that great Being,
who woos us to true happiness.
And indeed my whole delight was in the company of Christ my dear Lord and master.
I was directed by him to do all things well, and to bear all things with meekness.
As on my part I carefully regarded and practised his directions,
my soul enjoyed the sweet sense of his approbation.
I preferred this before all the world,
which I saw to be of little value compared with the favour of its Almighty Creator.
To please him I thought well worth all the toil and suffering of the day;
and the desire of doing it, increased my industry and strengthened my patience.
Thus I enjoyed a good time,
and was often overcome with the love and kindness of my dear Redeemer.

In him I had now a father, a guardian, and a friend, and an excellent one indeed,
who embraced me with the most engaging affection,
when I applied myself to do everything rightly.
All friends and relations, with all kinds of enjoyments seemed to centre in him alone,
for he alone amply supplied all, and having him was having everything that was good.
In his presence there could be no want.
It was then no hard matter for me to deny every corrupt desire, for his sake;
and to renounce the objects which had formerly pleased me too well,
and of which I had been foolishly fond; and yet for the rejection of these things,
which had done me no good, but harm, I ever found him a rich rewarder.

In his presence I could envy no man, however rich, eminent or seemingly happy;
but I loved all men as his workmanship, and wished that all would come to him,
and in and with him be truly happy forever.

Bidding farewell to the world and its vanities,
whose beauty and alluring lustre were tarnished and eclipsed in my eyes,
through the superior brightness of the Sun of Righteousness shining in my heart,
I loved solitude that I might seek him, who was now become the life of my life,
and wait for his fresh appearing to me,
who brought with him not only light to show me my blemishes and defects,
but animating fortitude, fervent desire,
and divine help to withstand and surmount corrupt habits and propensities,
and vigilantly, in the secret of the soul,
to guard against the first rising of any imagination, or inclination,
that was not consistent with the pure holy discoveries of his blessed Spirit.
Thus, with the royal Psalmist, Ps. 16:11.
"`In his presence I found fulness of joy.`"
My mind was moulded into a divine frame, a new creation of pure love to God and to men,
wherein the heavens and the earth in a sweet harmony, seemed to show forth the power,
wisdom and goodness of the one good Father and preserver of the whole.
I rejoiced that I had lived to see such a day,
wherein I had a sure evidence in my own bosom, of being translated to a better world,
to live forever united to him and his, if I should then be snatched from this.

Happy had it been for me, had I continued on steadily in my progress towards perfection,
through following his guidance towards it; but being in a great city,
I sometimes looked out, and thereby again raised sensual desires,
which demanded to be gratified, and were too often obeyed, when in my power,
by which I again did harm to myself,
and gave away my inward strength and fortitude for walking faithfully,
as Sampson gave away his to Delilah.
Yet I still bore a good character,
and many looked upon me as a young man of steady conduct;
but by a painful feeling of my own instability I knew myself better.

A good condition is easily lost,
for want of duly observing our blessed Lord`'s direction to watch and pray,
lest we enter into temptation.
While I observed this, I daily and hourly found the benefit of it,
in my rising up and lying down, and on my bed in the night season,
having my heart and affections wholly set on Christ,
and the great end of his having given me existence,
blessing his name for so revealing his goodness to me, renewing covenant with him,
and watching against every thought that had a tendency to carry away my mind,
and separate it from him.

I rose early, implored him to direct me how to spend every part of the day,
most to the honour of his name;
and to aid me to exert myself in the full discharge of my duty every way;
and O! many times in the day,
great peace and solid satisfaction flowed in my soul
for attending to and following his internal directions.
Everything went well and in proper order,
through this constant care to walk exemplarily,
and act faithfully in the duties of my place and station in life.
And many times in the evening of a well-spent day,
my soul overflowed with the sweet earnest of the heavenly and everlasting reward,
reserved for perseverance in well-doing.

Sometimes to every body that I saw, I felt great love to rise in my heart,
and a tender well-wishing desire for them,
that their souls might partake with mine of the hidden
treasures of the unutterable love of Christ,
and the joy of his salvation.

May I never forget the day of this his most engaging kindness, and of my espousals to him.
I may say truth is truth, unchangeably excellent, holy, pure and perfectly good.
It leads to everything that is best, and upholds in it,
and rewards for every act and instance of self-denial in obedience to its dictates.
Ever worthy to be admired, adored, reverenced,
loved and served by all the nations in the world,
as that which alone would make all happy in true love,
and preserve all in pure and spotless order everywhere.
So would earth resemble heaven, and its inhabitants be linked in a holy,
blessed society with Christ, with angels and the spirits of the just made perfect,
in enjoying together the brightness of his presence, in whose presence is joy,
and at whose right hand are rivers of pleasure forevermore.
For this our Lord prayed to his Father on behalf of his disciples;
"`sanctify them through thy truth, thy word is truth.`"

I continued in Bristol upwards of four years, living with my worthy master,
for whom I had a great and deserved esteem,
as assistant or usher in his school to the time of his death,
which happened the latter end of my fourth year there, he being seized with a disease,
which gradually weakened him,
till at last in a sweet frame of mind he departed this life,
generally regretted by friends and others, having been a man remarkably serviceable,
not only as a member of religious, but also of civil, society.
His character for integrity being so universal that he was very much
employed in determining differences between his fellow citizens,
either as arbitrator or umpire.

So that to the blessing of the peacemaker, he might seem to have a title above most.
His funeral from the Friars meetinghouse was attended
by a very great number of friends and others.
Four friends appeared publicly to a very crowded audience, viz. James Tylee,
Daniel Badger, Isaac Sharpless and Thomas Gawthrop.
The next day the men`'s meeting elected Jonathan Nelson, schoolmaster of Reading,
to succeed him,
and desired me to keep up the school till it might be convenient for him to come,
which I did, and at his coming resigned it to him.

1737.--Being informed that friends at Cork in Ireland, wanted a schoolmaster,
I agreed to go thither to serve them in that capacity;
so calling to see and take leave of my brother,
who lived with Thomas Bennett at Pickwick, in Wiltshire,
in the station of usher to his school, I went from thence to Gloucester,
and was at the two meetings there on first-day, which were poor small meetings.
On second-day I rode to Worcester,
and stayed there at my kind friend William Beesley`'s over third-day.
The week-day meeting there, was to me a tendering season,
both in silence and under the lively ministry of old John Corbyn.
Towards the week`'s end I reached Kendal, where I stayed two or three weeks;
during which stay, my father took a fever and died.
A day or two after his funeral, I left Kendal and returned to Bristol, from whence,
after waiting sometime for a wind, I took shipping for Cork,
in company with doctor Rutty of Dublin, who had been at the yearly meeting in London,
and amongst his relations in Wiltshire, and was also waiting for a passage to Cork.

I was affected with an awful impression on my first embarking;
which put me on considering on what foundation I ventured my life upon the water.
On that head I was soon favoured with inward satisfaction,
and resignation to divine Providence.

The wind being unfavourable, we had a very tedious passage,
being ten days on the water from Pill to the cove of Cork.
It was late at night when we landed at the cove,
and next morning went up in a boat to Cork,
where I lodged about two weeks at Jonas Devonsher`'s, a friend of a large estate,
his two sons being under my tuition;
and afterwards boarded in a friend`'s family till I married.

The meetings of friends in Ireland, and particularly in the province of Munster,
not lying so contiguous as in many parts of England,
could not so conveniently be joined several together,
to constitute monthly or men`'s meetings of discipline,
for transacting the affairs of the church.
In these parts each particular meeting was a men`'s meeting in itself,
and some of the meetings being greatly reduced in number,
it became the concern of friends to recommend to the larger meetings nearest to them,
the care of visiting these little meetings frequently, to inspect their state,
and help them by advice and counsel, as occasion might require.
Two of these meetings, viz:
those of Bandon and Youghal were under the care of Cork men`'s meeting,
which was constant in appointing visits to them at the stated times.

Being now a member of Cork men`'s meeting,
to which I was recommended by certificate from Bristol,
it fell to my lot in company with other friends,
to go upon a visit to the meeting of Youghal;
where I met with Mary the daughter of John and Martha Dobbs, of said town,
a plain and orderly young woman.
I found my affections closely engaged towards her;
and having proposed to her parents my desire to address her in order to marriage,
and obtained their consent, after sometime we were married there,
according to the good order used in our Society.

John Dobbs, her father,
being convinced of the truth while he was a student at the university of Oxford,
was for his fidelity to his religious convictions, disinherited by his father,
Richard Dobbs, Esq., of Castle-Dobbs near Carrickfergus,
of an estate worth several hundred pounds per annum, he being his eldest son.

His father left it to a younger son,
who was to pay my father-in-law ten pounds per annum out of it,
which during the lifetime of that son was but indifferently paid,
and by his prodigality the estate was involved.
But his son Arthur Dobbs, late governor of North Carolina,
succeeding to the inheritance thereof, voluntarily doubled the said annual sum,
and paid it punctually.
My father-in-law having studied physic at the college, practiced it with good success,
and great Christian charity to the poor, so as to save little from his income that way.

He had been the favourite of the family, but upon his joining in society with friends,
and giving up his whole heart to follow the discoveries
of the light of Christ in his conscience,
he was treated by his father with great severity as a rebel,
and then cast out as an alien.
So that he might well be said to have forsaken father and brethren, and sisters,
and houses, and lands for Christ`'s sake; and like faithful Abraham,
to have offered up to the Lord whatever was dearest to him in this world,
and to have trusted in God, which was doubtless counted to him for righteousness.

Being beloved by friends, he was urged by some to have recourse to the law,
for the recovery of the family estate as his birthright,
which he had done nothing to forfeit, and assistance offered him for doing it.
Whereupon he was prevailed with at length to make a beginning;
but not having that inward peace with Christ which he preferred before all the world,
in the first step of contention, he put a stop to all further proceedings,
and rather chose to confide in God without it.

For a more particular account of him,
see the [.book-title]#Collection of Friends`' Sufferings#, vol.
ii. and doctor Rutty`'s [.book-title]#History of the Rise and Progress of Truth in Ireland.#
Of him I have only to add, that he made a joyful and happy exit out of this world,
in an exceedingly thankful and triumphant state,
with a full assurance of going to live forever in a better.
He died about seven or eight months after our marriage.

His wife Martha Dobbs, was convinced of the truth before their marriage,
by the dying expressions of that handmaid of the Lord, Deborah Sandham.
She had a few words of public testimony in meeting, survived her husband some years,
and died in a good old age, having been a heavenly-minded woman.

Previous to my marriage, a small lot of ground offering for building on,
which was very convenient to my school,
and the carpenter reckoning he could run up a
neat small house for a sum I could then spare,
having in my employment in Bristol and here saved so much,
I adventured in conjunction with a friend, to take the ground and build upon it,
and the house was finished a few weeks after our marriage;
but the cost of it came to double the sum the
carpenter had proposed it might be built for.
This and some other things filled me with gloomy apprehensions,
and I became very dejected in my mind in consideration of my circumstances,
finding I had gone too far, and owed what I was not able to pay.
However, as my intentions were honest,
and my anxiety great that I might not by any misconduct blemish the truth,
which I had been instructed so highly to prize, by industry and frugality,
and through divine assistance, in some time I got over this difficulty,
and paid every farthing.

It may perhaps appear to some, that the recording of such transactions,
is of little importance or edification to uninterested readers;
but it hath not appeared so to me.
The account of these difficulties, which for want of due care and forethought,
and a constant, and deep attention to the unerring guide, we fall into,
though more humiliating, may perhaps be no less useful for caution,
than those experiences, which we can review with more heart-felt satisfaction,
are for encouragement and imitation.
Truth hath ever led to integrity, punctuality and upright dealing in our outward affairs,
and to limit ourselves to few wants, and an humble condition in life,
rather than invade or risk the property of other men.
We cannot all get a deal of the treasures of this world,
nor is it necessary to our well being.
"`A man`'s life consisteth not in the abundance of the things he possesseth,`"
but we may all live on a little,
if our minds be kept humble,
and the sensual appetites be subjected to the cross of Christ.
My view in relating how I was, undesignedly indeed,
involved in embarrassed circumstances, is for a caution to inexperienced young persons,
to be very considerate and careful in their expenses,
that they be neither lavish on things needless or superfluous,
nor in things otherwise convenient and lawful,
in a measure disproportionate to their ability to support clearly out of their own,
with honour, reputation and a good conscience;
for in this circumstance things lawful in
themselves are not lawful or expedient for them,
that so the profession of truth may not suffer reproach by their miscarriage,
as it hath done by that of too many others,
to the great regret of the honest and right-minded of our religious Society.

Furthermore, the narrative of these difficulties and anxieties,
that attended my first setting out in the married state,
seems to me to convey this instructive lessons to all single young persons,
who have not good patrimonies, or are not yet well settled in some business,
proper to maintain a family, that if they would do well in the world,
they should not be hasty in this weighty affair;
but consider wisely before they proceed toward it.
While single they have only themselves to care for,
and if they keep their hearts stayed upon the Lord, which is far easier for them to do,
than when weighed down under a load of care and encumbrances,
and come up faithfully in the way of their duty, they will be happy.
And by all means let them beware of entering into this most interesting engagement,
which is for life,
on which the happiness or unhappiness of this life very principally depends,
and by which that of the next may be very materially promoted or retarded,
till they see that the Lord opens their way, and conducts them in it.
Then the marriage will be honourable, the married will be like-minded,
standing in the counsel of best wisdom,
will be truly helpmeets to each other both in their temporal and spiritual concerns;
joining together with united and prepared hearts in religious and family duties,
and strengthening each other`'s hands for every good word and work;
minding the in-speaking Word, more than the attention or opinions,
the approbation or censures of the world.
Such if they have but little of earthly treasure are happily married.
But on any other terms, whether married or unmarried, people are not in a good way;
and it is infinitely better to be married to Christ,
than to be married ever so grandly in the world, out of the divine counsel and covenant.

As I had a religious desire in my choice, and that I might be rightly directed therein,
I had reason on the whole, notwithstanding these outward discouragements aforementioned,
to hope that I was so.
For my wife was the child of good parents,
from whom she had received a religious education, of orderly conversation,
innocent and well inclined, and we were in a good degree favoured together of the Lord,
she being free to give me up to every service I thought it my duty to engage in.
Upon my first visit to her,
the sense of truth and the solid edifying conversation of her worthy parents,
deeply fixed the best impressions on my spirit, so that in my return home to Cork,
twenty computed miles, my thankful heart was like a cup filled,
the tears of divine joy overflowed, and ran down my cheeks the greatest part of the way.
In this thankful frame I reached Cork, and my friends there,
who generally had a love for me, were pleased to see me,
and to hear such account as I had to give.
But then this good went off, and the instability of nature succeeded in a great degree,
though still mixed with a reverent view to the better part.

1739.--About four months after our marriage, being at a meeting at Youghal,
my heart was bowed in reverent fear,
and filled with the sweet influence of God`'s universal love.
It then appeared to be my duty,
in the clearness of that light and the strength of that love, to call to,
and invite those present to come to Christ, and yield grateful obedience to his laws.
I had been for several years before,
fully persuaded that this would be required of me as a duty,
and had desired never to dare to venture upon it until it should be so required.

Upon this duty being clearly presented to me in this meeting,
discouragements and obstacles poured into my mind in abundance, such as,
that if I should deliver the words imperfectly, I should be exposed to much speculation,
and become the immediate subject of conversation among
such as love to catch and propagate matter of amusement;
that perhaps the like duty might never be required of me again,
and in that case I should be likely to be talked of for many years,
as one who had begun and not gone on.
Instances occurred of such as had preached amongst us for a time,
and had either dropped it and fallen away, or had on one account or another,
incurred a public and general dislike or disgrace,
and that therefore it might be safer and better for me
to rest quiet with good wishes for the people,
and to exhort in a more private way, as I might have opportunity,
and a fresh concern on my mind.
These grounds of hesitation detained me till a friend
kneeled down to conclude the meeting in prayer.

I then saw clearly,
that if the meeting should break up without my uttering the exhortation,
which was fixed with so much weight upon my mind,
I should unavoidably incur the stings of conscious guilt, and the crime of disobedience.

Therefore not attending to the friend`'s public prayer,
my mind was earnestly and closely exercised in mental supplication to the Almighty,
that he would abilitate me to be faithful.
I had a hard struggle and conflict on this occasion;
but at length the power of divine faith prevailed,
to the shutting out and putting to silence all manner of discouraging apprehensions.
And when the prayer was ended I durst not sit down,
fearing I should not have power to rise again in time; but turning about to the meeting,
and seeing some of the people staring me in the face, such was my weakness,
that I raised up my hat, and holding it before my face, I spoke the words,
which had lain with weight on my mind, and sat down.
A flood of divine joy poured into my heart, and filled it all the day;
I went in this frame of mind into several friends`' families,
and my heart being still melted with divine love,
the tears of joy and thankfulness flowed down my cheeks,
which some ignorantly mistook for trouble of mind, saying one to another, they pitied me.

It was indeed a memorable day to me;
for I seemed to myself to be raised above the
sordid and sinful inhabitants of this world,
and to be admitted a partner of the blessed society of saints and angels,
and spirits of just men made perfect, through entire obedience rendered to their God.

I had a full assurance in myself, that if then sudden death should seize me,
I should immediately go to that blessed society,
to live in a holy and happy communion with them forever,
to adore that God and Sovereign, who had so infinitely favoured us.
And this is the very nature of that truly excellent religion,
with which our dear Redeemer came to bless mankind.

I might give some account of my services and of good effects
arising from my obeying the divine manifestation;
but accounts of that kind I leave to those who
have steered more steadily than I have done,
and think it more proper for me to look to the other side of my case,
and that with shame and confusion of heart,
mixed with humble admiration of divine goodness, which has hitherto been great,
and blest me with a few heavenly and good days,
wherein I should not have been afraid of death,
or of the awful and tremendous judgment which is to follow it.
Oh! that I may, through faithfulness on my part, attain the like again,
and that my last day may be my best day.
But alas, a consciousness of unfaithfulness in divers respects is my present companion,
though not with my will, or by design;
but through want of maintaining a proper vigilance and devotion,
and thereby losing the fortitude which I have sometimes been invested with.

Many of our dear, honourable friends of the first generation in our Society, appear,
from the time they were drawn to the pure fountain of light, life and love,
to have adhered thereto with immovable steadfastness to their last moments;
and a few I have known in my time who have arisen, and steadily persevered,
considering the degeneracy of the age,
in a faithful attachment of soul to that grace and truth, which is come by Jesus Christ;
and that have washed their robes white in his blood,
and have kept their garments unspotted.
But very few have come up to this height,
and so continued as with their feet fixed upon Mount Zion;
very few have got over the opposing mountains of human respect, selfish regards,
sensual appetites, desires of the ease, honours, or profits of this world;
all which tend to debase the soul, darken the judgment,
eclipse the brightness of heavenly light; blunt the edge of godly resolutions,
and contract the corrupting leaven and spirit of the world.

It is lamentable to reflect how many in our age,
even of the anointed sons and servants of the Lord,
have by these means gradually declined and dwindled, and at length totally fallen off,
as Judas did from Christ, and Demas from his faithful apostle,
and made shipwreck of faith and of a good conscience,
and brought lasting disgrace on themselves and that good cause
in which they had been humbly and honestly engaged.
Yet truth changes not; it is the same still, and still able to preserve from falling,
to build up, and to give an inheritance among the sanctified.

I remember that the above considerations made me earnestly pray,
that since I had given up, and put my hand to the plough,
I might never look back to Sodom again, like Lot`'s wife;
but rather suffer any thing in this world,
than disgrace the cause of truth and righteousness.

Encouraged as above, I proceeded to minister in public meetings,
when I had something given for that end,
through which exercise my gift became gradually enlarged.
But alas! I too often made false steps in my public ministry, as well as in my thoughts,
words and actions in private conduct,
for want of self-love being more mortified and subjected to the spirit of Christ,
which teaches divine wisdom.

Being of an active natural disposition, it became a cross to me to be silent,
when it was best to be so.
And sometimes after I stood up I continued too long,
till the testimony as to the life of it, flattened and grew tedious to the hearers.
I wanted too, to imitate some others, who I thought, preached finely.
Thus the enemy of man`'s happiness continually seeks to
tempt every class in the church militant.
As the eye is kept single to the holy Head, and the body full of light,
in the light he is discovered in all his approaches and transformations;
but I was not constantly enough on my guard against his stratagems,
and therefore was sometimes seduced even to think I did well, when I was zealous,
though not according to true knowledge,
nor to the honour of the great name of Christ our Lord;
for he is most honoured by the subjection of self; and by divine love,
coupled with humility and patience.

Among the many good institutions which the discoveries
of celestial wisdom have established in our Society,
is that of faithful elders appointed to watch over the flock, and over the ministry,
which has been found to be very useful.
And though the love of self-honour made me sometimes bear hardly the reproof of a friend;
yet I have afterwards, as in the cool of the day, discerned the expediency of it,
and been induced to desire to be more careful in future,
and to be willing to receive advice, as well as to give it.

O ye, whom Christ calls into the work of the ministry, or any other office,
give up your lives to him and it, both to do and to suffer what he may order or permit;
for the vessels of the Lord`'s house are to be of beaten gold.
Every son whom he loves he rebukes and chastens.
Then ever receive with a good mind, the counsel or the reproof of a friend.

If others revile and taunt in bitterness and wrath; in haughtiness and insult,
as whoever will live godly in Christ Jesus, must suffer persecution;
yet all things will work together for good to them that
steadily abide under Christ`'s government.
Our nature having in it much dross, and by long habit contracting an increase of it,
cannot be refined from it, but by fiery trials, nor have its evil humours purged out,
but by drinking the bitter cup.
Applause pleases the creature, but greatly endangers it.
Suffering in spirit, though more painful, is more safe.

O then! ye who have rightly begun, and favourably advanced in the work of truth,
or of the ministry, look well to your standing,
and guard against the transformations of your unwearied enemy.
When we first began, our single view and desire was to obtain divine approbation,
and that peace of soul, which results from it; to die to ourselves and all the world;
to know no man after the flesh, nor be known by them; but only to know the Lord,
and to walk and act under his immediate notice and approving favour.
But afterwards there hath mingled herewith, the desire of human notice,
of popular applause, of worldly advantages and indulgences.

Thus some ministers, as well as others, who have given up their names to follow the Lamb,
have slipped into a mixed state.
In them the spring once pure, hath become muddy, and the sacred fervour hath dwindled.
Though they have retained the form of godliness,
yet its conquering power and fortitude have gradually died away,
and left them as weak and unable to resist temptations,
as those who have never assumed that form.

This has been the case of many dry worldlings and sensualists in our Society, who,
far from helping the cause, which they professed a value for, have greatly hurt it,
and given a handle to libertines to make both it and them, the subject of their derision.

When the humble regard and love of God singly presided in my heart,
then I have been disposed to receive the advice or the rebuke of a friend,
in the love in which it was given, and to bear with Christian meekness,
the taunts and insults of insensible hearts and unguarded lips, undisturbed thereby;
but when I have slidden off this foundation, then they have discomposed my mind,
and agitated it with selfish and uneasy resentments.

I have not so often met with this kind of returns to my ministry, as applause,
which indeed is an intoxicating and pernicious cup for any to drink without great fear.
It raised the spirits with a false alacrity; elevates the mind with self-conceit,
and an imagined superiority to others, leads into an evil emulation,
and even to slight those who are in a much better state,
dwelling in the valley of humility, subject to Christ the beloved of their souls.

It is hard for the creature not to be pleased with praise, and to offer it to him,
to whom alone it is due; or after being at any time signally honoured,
to return like Mordecai, dismounted, stripped of the royal robes, and to sit in a silent,
abject condition, at the king`'s gate, waiting on him in poverty of spirit.

As applause is dangerous, so the affections of the people,
if not kept under proper government, both by the minister and his hearers,
have a snare in them, as indeed hath every object of our senses,
without maintaining an inward watchfulness;
these things not being the proper mark or prize of a minister or a Christian.
It is base to play the harlot with corrupt self, and deck it with the Lord`'s jewels.
For if we take these rewards of our labours,
we are in danger of losing that which he gives to the faithful,
which is the one true and durable reward.

The spirit of the gospel directs us, to submit ourselves, or give way, one to another,
to be abased, and prefer others; the strong to take the weak by the hand,
and all to imitate the holy pattern of Christ, who was meek and lowly in heart,
and stooped to wash the feet even of his disciples and servants.

It was he by his Spirit, who not only raised up a living ministry in our Society,
but by the same spirit animated our faithful
predecessors to establish a salutary discipline therein,
upon the same foundation; and raised up and gifted men and women for valuable services,
conducing to the edification and strengthening of one another in piety.
Often have I sat in meetings of discipline greatly humbled,
tendered and revived in my spirit,
with fresh resolution to renew my diligence in my journey heavenward.

One branch of this discipline, viz: the institution of meetings of ministers and elders,
I highly regarded.
For when we have, in a sense of our entire inability without his help,
prostrated ourselves together before the most high God,
he hath graciously vouchsafed to open the living springs of counsel,
suitable to the several states and stations present,
tending to stir up to diligence and devotedness in his service,
and pointing out in the opening of gospel light,
the snares and dangers waylaying the spiritual traveller in his journey.

Often have these meetings, when we have been thus prepared for them,
cemented us together in an humble engagement of soul toward God.
Tender love hath abounded, which hath made us dear one to another,
as children of one family, and fellow-labourers in the highest and best cause.
Christ our Lord has favoured us with his presence and sovereign power,
and made us partakers together of his heart-tendering goodness,
and of a near communion and divine fellowship with him through his Spirit,
and with each other therein, renewing our ardent concern for the honour of his Name,
and the promotion of his truth.

But when this preparation has been wanting,
and inattention and absence of mind have taken place,
then we have been barren as the dry heath; and like the earth, covered with darkness,
without form and void, when the spirit of the Lord moved not on the face of the waters.
Both the immediate and instrumental springs of lively
and clear counsel and consolation have been closed up,
and the edification and watering of the flock withheld.
This hath caused living zeal, and even the attendance of those meetings to decay,
and to yield to temporal affairs and temptations, to the hurt and loss of many.

May these considerations move ministers and elders more particularly,
to seek after the preparation requisite for assembling in the name and power of Christ,
and under a renewed concern for their individual preservation,
as well as for that of their brethren and sisters,
that they may thereby be comfortably enlivened, and enliven one another to all goodness,
as men and women redeemed from the world, and fellow-citizens of the New Jerusalem.
Then, of great and valuable benefit indeed, would these solemn meetings be,
as heretofore, when faithful labourers in the Lord`'s service, dignified,
adorned and upheld them.

When I had resided about three years in Ireland, my brother John,
whom I left in the service of Thomas Bennett, at Pickwick, Wilts, as noticed before,
being desirous to fix his residence in the same nation with me,
at the expiration of his fourth year there, resigned his place of usher to that school,
in order to remove to Ireland; and going first to see our mother and relations at Kendal,
she concluded to accompany him in order to pay us a visit of a few weeks,
and about the middle of the summer, 1740, they both arrived at Cork.
After about five weeks abode with us, my mother inclined to return home;
and I having a concern on my mind to visit my native country in the service of Truth,
my brother`'s arrival opened the way to set me at liberty--he
willingly taking charge of my school in my absence.

I concluded to accompany my mother in her return;
and having laid my concern before the men`'s meeting and obtained their certificate,
and soon meeting with a vessel bound to Whitehaven, we embarked therein,
and had a favourable passage, being only about forty-eight hours from port to port.

This journey took me up about five weeks,
in which time I visited the meetings of Friends pretty generally,
through the counties of Cumberland, Westmoreland and Lancashire,
and part of the north of Yorkshire,
being frequently much favoured by the Master of our assemblies,
and often enlarged in the love of the gospel amongst my former relations,
friends and neighbours, many of whom were glad to see me,
and I was nearly united to them in the unity of the one spirit, the bond of peace.

[.offset]
+++[+++Here a sheet of the original is lost, which I have not been able to recover;
I regret the loss, not only as it occasions a chasm in the narration;
but by the recollection I have of my brother`'s
epistolary and verbal relations of this journey,
I apprehend we are deprived of some occurrences, worthy of preserving.
One in particular I have heard him relate in terms so lively and affecting,
as indicated it had fixed a deep impression on his mind; so that,
I think he would not pass it unnoticed.
When he came to Pardshaw meeting in Cumberland,
he received intelligence that our ancient valuable friend,
that faithful minister of the gospel in his day, James Dickinson,
was then confined by sickness, and apparently near his close,
whereupon he went to pay him a visit, and found him in such a happy,
heavenly frame of mind, as made the opportunity very tenderly affecting and edifying.
Raised above the world he was departing from,
and well prepared for that celestial mansion,
he was favoured with a lively hope of being shortly admitted into;
in this his concluding scene, amongst other affecting expressions he related of his,
I recollect the following, in purport;
"`I have served the Lord and his truth in my generation,
and now I feel the blessed reward thereof:
the accuser of the brethren is cast down as to me,
and my peace with God is sealed forever.`"
This, he related was delivered in such a feeling, powerful and affecting manner,
as greatly tendered his spirit, and left the best impressions upon it,
animating him to fresh and ardent desires, so to fulfill his ministry,
and walk through life, as that he might die the death of the righteous,
and that his last end might be like his.
And indeed, what scene in this life more dignifies humanity?
What school is more profitably instructive than the deathbed of the righteous,
impressing the understanding with a convincing evidence,
that they have not followed cunningly devised fables, but solid, substantial truth;
that there is a measure of divine light and grace in man,
which if duly minded and obeyed,
is sufficient to preserve through all the vicissitudes in life,
to give him the victory over his spiritual enemies, and in the end over death,
hell and the grave.]

[.offset]
Returning to his Journal--

I was at a general meeting at Crook, about four miles from Kendal,
which was eminently favoured, and after it, went to lodge at Lydia Lancaster`'s,
a valuable minister, and a mother in Israel.
Next morning went to their meeting at Colthouse near Hawkshead,
and after meeting went to William Rawlinson`'s to lodge.
Next morning in very wet stormy weather, I went to Height meeting.
Most of the friends belonging to it lived at some miles distance;
yet they generally attended, and I believe were thankful that they did so,
the cementing virtue and power of the gospel so prevailed therein.

After meeting I went with James Rowlandson`'s family to his house at Frith.
His daughter Jane had for a little while past appeared
at times in the public ministry in our meetings.
So much of tenderness, and of inward fervency toward Christ the beloved of her soul,
prevailed in her, as to make deep and lively impressions on my mind.

Next day, that family accompanied me over the sands to a meeting at Swarthmore,
and I returned with them, and from thence back to Kendal.
The said Jane Rowlandson afterwards married George Crosfield, became a valuable minister,
visited Ireland twice while I lived there, and the continent of America once.

In the course of this journey I was favoured with the
company and countenance of sundry friends,
whom in my younger years I had held in estimation,
by reason of the good impressions I received from their exemplary lives and labours,
as before noted in its place.
My quondam master, David Hall, treated me with affectionate respect;
he had buried his former wife, who was my mistress, and married again.
He and his wife accompanied me to a meeting at Airton.
I lodged at Thomas Anderson`'s, a friend in the ministry,
who visited Ireland in company with David Hall; he was blind,
but exceedingly pleasant and cheerful.
Next morning being a hard frost,
I went with said Thomas and other friends over a
great hill to a monthly meeting at Settle.
By me in the gallery sat Julian Frankland, a good old woman, near ninety years of age,
and a good meeting it was.

At and about Kendal also,
I had much of the company of that honourable minister and elder, James Wilson,
who as a nursing father encouraged and strengthened me in the service I was engaged in.
His conversation was often pleasant, instructing and edifying;
one remarkable passage he related, I think worthy of inserting,
which was to the following purport.

In his young years,
having been educated in the established religion or church of England so called,
he had conceived a very contemptible opinion of
the people called Quakers and their principles,
and at a public house falling in company with some others of like sentiments,
this people became the subject of their discourse;
and as they were expressing their sentiments of
contempt and dislike of them pretty freely,
a person of some note, who had been an officer under Oliver Cromwell, came into the room,
and overhearing their discourse, observed to them in substance,
"`That he apprehended their prejudice towards this
people arose from their want of knowing them;
for my part, continued he,
I entertain very different sentiments of them;`" and
perceiving them struck with admiration to hear him,
whom they looked upon as a man of sense, as well as consequence,
express himself after this manner, he proceeded to the following purpose:
"`You seem to wonder that I express a favourable opinion of the Quakers;
I will inform you the reason.
After the battle of Dunbar, as I was riding in Scotland at the head of my troop,
I observed at some distance from the road, a crowd of people,
and one higher than the rest;
upon which I sent one of my men to see and bring
me word what was the meaning of this gathering;
and seeing him ride up and stay there, without returning according to my order,
I sent a second, who stayed in like manner; and then I determined to go myself.
When I came thither, I found it was James Nayler preaching to the people;
and with such power and reaching energy, as I had not till then been witness of.
I could not help staying a little, although I was afraid to stay;
for I was made a Quaker, being forced to tremble at the sight of myself.
I was struck with more terror by the preaching of James Nayler,
than I was at the battle of Dunbar, when we had nothing else to expect,
but to fall a prey to the swords of our enemies, without being able to help ourselves.
I clearly saw the cross to be submitted to, so I durst stay no longer, but got off,
and carried condemnation for it in my own breast.
The people there, in the clear and powerful opening of their states,
cried out against themselves, imploring mercy, a thorough change,
and the whole work of salvation to be effected in them.
Ever since I have thought myself obliged to acknowledge on their behalf,
as I have now done.`"

This, James Wilson said,
proved the first step towards his convincement of our principles,
inclining him to go to our meetings, which, before he had an aversion to the thoughts of,
from the prejudice above hinted.
In those days the meetings of friends were more eminently favoured with divine power,
as they lived more devoted to Christ;
and consequently more abounding with his love flowing in their hearts.

I was ready to think that Isaac Alexander had been instrumental to his convincement.
I find it recorded in the third volume of the Dying Sayings,
that said Isaac died at his house.
Of him he gave me the following account; that "`being in himself an illiterate rustic,
soon after his convincement he appeared in the ministry in a lively and powerful manner.
A neighbour of his, having heard of his becoming a preacher,
could not tell how sufficiently to express his admiration;
he made it the subject of his discourse from place to place,
deriding him who had no learning for presuming to preach,
and the people for suffering him.`"

"`This man attended the funeral of that great and good woman, Ann Camm.
The meeting proved an exceedingly enlightening, tendering opportunity;
and even this derider was contrited and humbled therein.
Isaac Alexander was eminently raised up in his gift,
to set forth the goodness and the justice of God; the glory of truth,
the happiness of obeying it,
and the lasting infelicity of neglecting and rebelling against it.
The man was so thoroughly penetrated with a clear sight of his own case,
that after Isaac had done, he stood up in that very assembly,
acknowledged the crime he had been guilty of,
and begged the prayers of all good Christians, that it might be forgiven him.`"

I mostly finished my service in England in this journey,
with the quarterly meeting for Lancashire, at Lancaster, and that for Westmoreland,
at Kendal, held in succession.
At the former, I met with Abraham Fuller, of Dublin,
who had accompanied Moses Aldridge from New England,
in his religious visit to friends in Scotland, and was now, as well as myself,
on his return home; our meeting being quite unexpected,
was a very pleasing surprise to us both,
especially as we were likely to be companions to Dublin.
Here also, I met with Samuel Fothergill, then young in the ministry;
but even then appearing with a solemnity, brightness, and gospel authority,
which gave friends lively hopes of his proving, as he did,
through the succeeding stages of his life, a bright and shining light,
a vessel of honour indeed, of eminent service in the church of Christ.
The public service in the said quarterly meeting, fell to the share of us who were young,
though many weighty, experienced ministers were present,
and our good Master being with us, it proved a refreshing,
satisfactory and edifying meeting.

From Lancaster we went directly to the quarterly meeting at Kendal,
which was also a good meeting,
and the beginning of the succeeding week we proceeded to Whitehaven,
in order to take shipping for Dublin, where we arrived on seventh-day following,
and I lodged at Joseph Gill`'s. I attended the meetings there the next day,
and heavenly help being near, I was furnished with ability and matter,
to minister to the general satisfaction and edification of friends,
and the ease of my own mind.
And my being at that time quite a stranger to most friends in that city,
and coming quite unexpectedly, occasioned pretty much inquiry among them.

From Dublin I proceeded toward Limerick, by Mountmelick, Mountrath, and Kilconnermore,
where John Ashton was then living; a valuable good man,
little inferior to most I have known, in my estimation.
Although not eminent for great and shining parts;
yet he was a shining light in the country where he resided, in love and good works;
a man of great humility and fervour of soul for the promotion of piety;
much beloved and esteemed of his neighbours and friends.

When I came to the good old man`'s house, being now near eighty years of age,
he was very much indisposed; and it being about the middle of the eighth month, O. S.,
or October,^
footnote:[Until 1752, March was considered the first month of the year
in all of England and its colonies. O. S. stands for Old Style, referring to the
former way of reckoning months according to the older Julian calendar.]
and the friends in that part being late with some part of their harvest,
he proposed, notwithstanding his infirmity, to accompany me to Limerick,
a great day`'s journey for him when he was well, as the roads were then;
and his relations,
apprehending it too hazardous for him to undertake under his present indisposition,
endeavoured to dissuade him from it;
which made me desirous that he might not suffer in his health,
or meet with any dissatisfaction of mind.

It proved a fine day; he grew much better, and his conversation was very edifying.
Our friends at Limerick rejoiced greatly to see him,
being the last time of his being there.
Next day being first-day, we had two comfortable meetings there.

On second-day morning at parting, he told me, he was well paid for coming.
He was well and hearty the winter following,
and the next spring set forward towards the half-year`'s meeting at Dublin,
but having reached Birr, he found himself unable to go further, returned home,
and after a short illness departed this life,
leaving behind him a general testimony all round the country on his behalf,
as one who had eminently served God, loved mankind,
and was greatly beloved by almost every one who knew him.

He and his wife were both convinced at one meeting at Birr,
through the powerful ministry of that able and eminent minister of the gospel,
Thomas Wilson.
Coming out of that meeting, they said to each other,
"`The way of everlasting happiness had been clearly laid down before them,
and they were resolved to walk in it, come life, or come death.`"

Not long after,
John was thrown into prison for his Christian testimony
against the oppressive and anti-christian yoke of tithes.
Being used to work without doors, he was at a loss how to employ his time;
but soon learned to make gartering and laces.

When at liberty, he with his wife, constantly twice a week attended the meeting at Birr,
generally walking on foot thither, being about seven English miles, and a very bad road,
wading through a river in the way, both going and returning.
In winter, in crossing this river, they sometimes had the ice to break;
and John said he had wept to see the blood on his wife`'s legs in coming through it.
In those days truth was precious to its professors, who also possessed it,
and no difficulties or dangers could prevent
them from getting to their religious meetings,
to enjoy the renewings of divine love and life, with their brethren.

This good man also took great pains to get travelling
friends to appoint meetings at his house;
and then to acquaint people thereof, several miles round,
travelling for that purpose by night, as well as by day,
in the winter season and in severe weather,
and underwent much reproach for this labour and diligence.
Yet he was blest in it, both inwardly and outwardly,
many came to the meetings at his house, several were convinced of the truth,
and in process of time a meeting was settled there, and grew larger than that of Birr,
out of which it had sprung.

At the time of his joining our Society, he was in low circumstances,
but through industry and the blessing of heaven he grew rich, and did abundance of good,
being singularly hospitable, liberal and charitable.

At the above-said meeting at Birr, through the ministry of Thomas Wilson,
there was also convinced, his wife`'s daughter Mary, the wife of James Sheppard.
This was a great mortification to her husband, who tried various means to reclaim her.
At length a noted preacher being to preach at the worship house he frequented,
he proposed to his wife, that if she would go with him to hear him,
he would go with her next Sunday, as he called it, to the meeting at Birr,
to which proposal she assented.
She went accordingly, and heard fine words and eloquence;
but that was not what her soul wanted.

Next first-day, pursuant to his engagement, he went with her to Birr.
It proved to be a silent meeting there;
yet through the reverent attendance of the souls of those present upon Christ,
the best minister, they were favoured together with his life-giving presence,
with the sense of which the said James was reached and tendered into contrition,
in the sight of the self-denying path cast up to peace with God.
Hereupon, what he little expected at his going to that meeting,
he immediately joined in society with friends,
and became a serviceable man in his station.

After parting with John Ashton, I proceeded toward Cork,
and reached it next morning before meeting.

Soon after, I visited some parts of Leinster province.
After my return I spared my brother, at the request of Benjamin Wilson, near Edenderry,
to be tutor to his children, and those of a neighbouring friend.
When he had been there about a year and a half, I wrote to him to prepare,
after duly apprizing his employers, to return to Cork, having a desire for once,
while I had an opportunity of his supplying my place, to be at the Welch, Bristol,
and London yearly meetings; and though the family was loath to part with him,
yet as I wanted him on this account, he disengaged himself and returned to Cork,
in due time for me to proceed on the service before me.

Accordingly, in the beginning of the first month, O. S., now called the third,
I embarked on a sixth-day morning at Cork; on seventh-day at night,
by favour of the lighthouses, we got into Milford-haven.
On first-day morning I walked to Haverford-west, where I met with Abraham Fuller,
of Dublin, whom I consulted how I should steer my course to North-Wales,
as I understood here,
that the Welch yearly meeting was to be about a month from this time,
in this neighbourhood, viz: at Tenby in Pembrokeshire.

Abraham advised me to order my course so, as to be at John Goodwin`'s on a first-day,
because there was generally a large resort of people there on that day,
and gave me directions how to accomplish it, which I was pleased with,
having heard before of that good old man, and having a desire to be then at his house.

On third-day after meeting, I left Haverford-west,
and had a meeting next day at Carmarthen;
on fifth-day morning went to John Bowen`'s at Penplace, expecting to have a meeting there,
but he being gone to their monthly meeting at John Recce`'s at Penbank,
I followed him thither, where I found a considerable number met.
After I had sat down, old John Reece stood up and preached to us in Welch.
On sixth-day I went to the widow Evans`'s at Llandewy-brevy, in Cardiganshire,
and expected next day to reach John Goodwin`'s, at Escargogh in Monmouthshire.

Next morning the friend who was to have been my guide,
came into my chamber long before day, when I was about getting up,
having an earnest desire to reach John Goodwin`'s that day.
He informed me, I could not go thither that day, without running the risk of my life,
as it snowed very hard, and it was a mountainous road.
I presently got up, and found myself obliged to stay there,
to the no small disappointment of my desire, I then went to their market-town,
called Tregarron, and there had two meetings that day, the latter of which was large.
Next day being first-day, hearing of a priest called Daniel Rowland,
whose parish worship house was at Llangeithow, three miles beyond Llandewy-brevy,
who was much flocked after by many people, even from other parishes; thither I went,
accompanied by three friends.
When we arrived we found the house full, and many at the outside,
who seemed to listen to the preacher with attention, who was preaching in Welch.
I desired a young man to endeavour to get to the parson,
and acquaint him that an Englishman without wanted to speak to him,
which I suppose he did.
For when he had ended his sermon the congregation broke up,
and he came out one of the first.

I went to meet him and told him,
I had found my mind drawn in Christian love to visit him and his congregation,
and therefore desired then the opportunity to
deliver to him and them what was on my mind.
After some inquiries, he said it was not convenient then,
as he had himself preached largely to the people.
Finding myself clear of him, I got upon a pretty high tombstone,
and the people generally drew near, being a very large multitude.
The opportunity was greatly favoured, I being engaged to invite the people to Christ,
the free teacher, and of him to receive wine and milk,
strength and nourishment to their souls, without money and without price:
though the people stood close crowded,
there seemed to be as great a stillness as if scarcely any were there.
After I had ended what at that time flowed through my heart to them,
I stood a little with my mind reverently and thankfully affected.
At length I looked round to see on which side I might most easily retire.
Some of the people near, who perceived it,
desired that I would pray for them before I left them.
I answered, that I did indeed pray for them; but as for doing it vocally, I durst not,
unless it appeared at that time to be my duty so to do.
They asked then, whither I intended to go next; I told them, to Llambeter,
about five miles off, where I intended to have a meeting that afternoon.
Thither many of them went.

When I had got a little way on the road,
I was overtaken by one who looked like a gentleman, on horseback,
with his wife riding behind a man on another horse; he told me,
he had come out of Carmarthenshire, fourteen miles over the hills,
to hear Daniel Rowland; asking if I should come into that county; that if I did,
he would meet me any where in it, if he could know the time and place;
but would be better pleased if I could come and lodge a night with him,
which I afterward did.

As I advanced a little further, a certain woman, not of our profession, invited me,
and friends with me to dine, and gave us the best entertainment in her power.
She expressed with solidity, she had not understood one word I had said;
but had felt that which had done her heart good, as a friend interpreted her words to me.

Many people flocking to Llambeter, the meeting was held in the street.
After it I parted with the people in mutual affection, and returned to Llandewy-brevy,
in company with friends and others.
I was at this time much overcome with the Lord`'s goodness,
and thankful for the aforesaid disappointment of my desire,
believing it to be in the ordering of best wisdom, for the service of the day,
being filled with a comfortable hope I was in my proper place,
which caused the tears to run down my cheeks, most of the way I had to ride.

When I returned to my quarters, at the widow Evans`'s, near Llandewy-brevy,
a great number of the neighbouring people were come thither,
and an unexpected meeting ensued,
wherein several were broken and tendered in the time of silence.
I briefly observed, that it had been made a good day to several of us,
expressing my desire that it might be duly remembered by us.
And in this lively tenderness we took our leave of one another.

But alas, when I came thither eighteen years after this,
I found little sign left of that fervency toward God,
which then seemed impressed on their minds.
The enemy had got entrance, and much stolen it away.

Next day I got to John Goodwin`'s, and he told me,
he believed I was come in the right time,
there having been but few at his house the day before,
by reason of the snow that had fallen thereabout.
He accompanied me from his house to a meeting in the edge of Shropshire.

John told me,
that his father and mother were both convinced of truth about the same time,
and received it in the love of it.
At that time his father was clerk of the parish, and master of the free school thereof;
but upon his joining with friends, and giving up faithfully to divine conviction,
he was turned out of both these places, and obliged to have recourse to hard labour,
wherein his mother heartily joined; but, that himself, their eldest child,
then well grown toward the state of a youth, not understanding their case,
thought them fools to turn Quakers, and resolved he would not be like them in that;
nor did they offer any compulsion to him therein; but their prayers,
put up to the Lord for him, were manifestly answered,
and they had in their son the comfort they desired.
At this time friends were grown numerous in Wales; but soon after,
upon the encouragement given by William Penn,
most of the friends in some parts of this principality,
removed and settled in Pennsylvania, and amongst the rest John`'s father and mother,
with most of their children.
From inclination he would have removed with them;
but a higher power directed his stay in his native land,
and to that he gave up father and mother and everything.
This good man recounted the great favours of the Lord to him all along to that day,
to the following purport.

"`When the Lord pointed out poor Wales as a field of labour for me, he promised,
that if I was faithful to him in it, he would be with me and favour me therein;
and now I have in my heart a testimony for him in my old age,
that he hath abundantly made good his promise to me, both outwardly and inwardly,
far beyond what at that day I could have expected.`"
Which favours, in divers respects he related to me in a very edifying,
thankful frame of mind.
And speaking of his wife in particular, he related the steps by which the Lord,
whom they loved and served, conducted and joined them together; adding,
"`I think I may say, if ever man in the world got his right wife, I got mine.`"
He further told me,
that he lived and maintained his family on a farm of four pounds a year,
but at length had purchased it and improved it,
so that at that time he reckoned it worth six pounds a year.
The first journey he travelled in the ministry, being to visit friends through Wales,
he had then got of clear money, above forty shillings in all;
and he was free to spend it, if there was occasion, in the Lord`'s service,
knowing that he could give him, or enable him to get more;
that the first time he began to entertain travelling friends,
most of the meeting being then gone to Pennsylvania, he had but one bed,
which he left to them, he and his wife taking up their lodging in the stable.
Divers have been convinced by his ministry;
and one of the principal worthies of our age I have esteemed him.

The foregoing narrative of this worthy elder, was edifying and profitable to me,
not only at the time, but frequently since, in the review and recollection thereof;
and I thought it worthy of recital,
as conveying profitable instruction to every class of readers,
whether of high or low degree--to the former a lesson of instruction,
how humbly thankful they ought to be to the gracious Giver of all good things,
for his extensive bounty to them.
When we consider this truly good man, in circumstances we should reckon mean indeed,
and a manner of living suitable to his circumstances,
bearing a lively and grateful testimony to the goodness,
mercy and truth of the Lord in his gracious dealings with him; also,
when he dedicates his little all, in faith, to his Lord`'s service,
doth he not in the silent and reaching language of example,
convey this intelligence to thy soul, who art blessed with abundance?
"`Go thou and do likewise;
honour the Lord with thy substance and the first fruits of all thy increase; love mercy,
and walk humbly with thy God;`" deeply pondering in thy heart,
"`How much owest thou to the Lord!`"

Those of low circumstances from hence may learn,
that happiness is confined to no station in this life;
but is the result of observing the law of God in the inward parts, being,
as it prescribes, content with the things which we have, not minding high things;
but reducing our desires to the level of our station in life,
that so we may fill it with propriety and act our parts well.
If we thus walk by the unerring rule of truth, though we be esteemed poor in this world,
we shall be rich in faith, and with this worthy man,
enjoy in the obscurity of the humble cottage, what palaces too seldom afford,
solid content, the consolation of a conscience void of offence,
and the reward of well-doing,
"`the peace of God that passeth the understandings of men.`"
The most splendid and extensive earthly possessions,
when laid in the balance against durable possessions like these, are indeed as nothing,
and lighter than vanity.

Having parted with John Goodwin, I went to Shrewsbury, Colebrookdale, Bewdley, Worcester,
Birmingham, Coventry, Warwick, Evesham; then back by Worcester to Bromyard, Hereford,
Amely, and into Radnorshire in Wales, to Brinfloyd and Talcot,
To this last place came Mary Rickerby of Yorkshire, from Llandewy-brevy much tired;
but after a little rest and refreshment, she had an edifying opportunity in the family;
and from hence she, with Miriam Bowen, and her uncle Edward Jones,
accompanied me to the Welch yearly meeting, as did also John Young, from Leominster,
who met me at Hereford for that purpose, and was an acceptable companion.

Next morning we set out from Talcot about five o`'clock,
and got to Nathaniel Anthony`'s a little after meeting time,
a meeting having been appointed beforehand there, to begin at five in the evening.
After meeting,
John Young and I went to lodge with that couple
who had before invited me near Llangeithow,
where we met with a kind and cordial reception,
and found them fervent in desire after godliness.
Next morning we met Mary Rickerby, and sundry other friends at John Bowen`'s.

Thence went to an evening meeting at Carmarthen, which was large.
Next day being seventh-day, we went to John Lewis`'s house in the country.
On first-day with him to the meeting at Redstone,
and in the afternoon were at a large meeting at Haverfordwest; and from hence,
on third-day, we went to the yearly meeting at Tenby.

After the yearly meeting, I went by Swanzey and Trevereeg to Pontypool,
being accompanied by good old Evan Evans.
Thence by Shernuton and Ross to Gloucester, and from thence round by Oxfordshire,
Berkshire and Wiltshire to Bristol yearly meeting; and from thence by Bath, Bradford,
Shaftsbury, Poole, Ringwood and Southampton, and the Isle of Wight, to that of London.

At Shaftsbury the meeting had been pretty much dropped for several years,
there being none of our profession left, but an old friend, a tanner,
and his two sisters; but at this time several were in part convinced,
and thereupon the meeting revived, I was there on a first-day, and had three meetings,
which were large.
The second-day I spent in visiting families,
and in the evening had a concluding meeting with friends, and those newly convinced.
It was a satisfactory time; and one man`'s wife who had been in great grief,
passion and bitterness, on account of her husband`'s joining in our profession,
was herself gained, and joined him and friends,
and another woman likewise joined us at the same time;
yet the fervency which was then felt, proved but of short duration with several of them.
However, the meeting has continued,
a new meeting-house has been built there since that time,
and the quarterly meeting of the county of Dorset is sometimes held there.

On my return from the Isle of Wight,
Thomas Whitehead and Philip Elliot met me at Portsmouth,
and accompanied me thence to London, with young Abel Plollis, of the Isle of Wight,
who was then hopeful.
Next day being the fourth of the week, we came to Alton;
after meeting there on fifth-day, we came to an evening meeting at Godalming.
Sixth-day morning were at a meeting at Guilford; after which,
being joined by Samuel Bownas and Jeremiah Waring, we came to Esher,
and next morning to London to the yearly meeting.

In this journey, Samuel Bownas was particularly kind and fatherly to me.
We were together at Gracious street meeting on first-day morning,
which was a good meeting, and wherein I was favoured in a good degree.

Thomas Whitehead and Philip Elliot accompanied me after the yearly meeting was over,
to a meeting at Hertford.
From Hertford I went to Hitchin, Jordans, High-Wiccomb, etc.:
was at the quarterly meeting at Okeham, for the counties of Leicester and Rutland,
and at those at Lincoln, York, Lancaster and Kendal.

At this yearly meeting were no representatives
from Ireland but Abraham Fuller and I. John Pim,
of Edenderry, and his brother Joshua Pim of Mountrath, came as far as Coventry;
and there the said Joshua, a valuable friend and elder, was visited with a distemper,
which for a time seemed dangerous.
He recovered, but not till sometime after the yearly meeting was over.

The like afterwards happened to another good friend and elder, Joseph Williams,
of Randall`'s Mills, who reached London,
and was there by indisposition prevented from getting out to any meeting;
such trials being sometimes permitted,
for proving and exercising the faith and patience of the Lord`'s servants.

In this journey I often travelled hard, and had two meetings a day wherever I could.
It took me about five months.
At Lincoln quarterly meeting friends lodged at inns.
I do not remember that I knew one friend there, but John Scott, from Leeds,
and May Drummond.
It being now about midsummer, the public meeting began at twelve o`'clock,
their men`'s meeting about two, and ended before four.
In those two meetings I had been shut up.
I met with an elderly friend,
and asked him how friends spent the residue of the long evening; he answered,
"`In conversing together, or taking a walk or the like.`"
I told him, I thought it was a pity,
considering the large number of young people who
came together from different parts of the county;
and that the end would be better answered, by some religious opportunity or meeting,
that might tend to edification, and be of benefit to some at least.
He replied, "`They used to have evening meetings;
but being on one hand much infested with rude people,
and on the other too often weakly conducted, they did not prove satisfactory;
and for these reasons friends had thought it best to discontinue them.`"

Hereupon we were called in to dinner, but I had little appetite;
after dinner I was called out.
Some of the elders had drawn together, and upon my coming to them,
signified if I had a concern for an evening meeting, they were willing to appoint one,
to begin at the sixth hour.
I was afraid, yet durst not refuse the proposal; so upon my assenting,
the meeting was appointed.
It was much crowded, and the life and power of truth was in dominion,
which eased my mind of its burden and filled it with thankfulness.

From hence, John Scott, May Drummond and I, with divers other friends,
came to a meeting at Gainsborough, and on the first-day after,
were at the general meeting at Warnsworth, where we met with Joseph Storr.
From thence John Scott and I went to the monthly meeting at Leeds,
where we met with our valuable ancient friend, William Slater.
From Leeds I went in company with William Hird and his wife,
to the monthly meeting at Knaresborough, at which was John Fothergill;
and from thence to the quarterly meeting at York, to which came John Richardson,
who was expected by few, having been thought to be near death for some time before,
but being recovered a little, though still very feeble in body, but strong in faith,
and warm in love to God and the brethren, in a journey of three days,
which he had used to accomplish in one or less, he reached this city,
to have one more solemn opportunity with his friends at this meeting.

In the meeting of ministers,
the good old man was enlarged in much weighty and pertinent counsel,
in the clear openings of gospel light;
but the public meetings were much hurt by raw and forward public appearances.

From York I came with Mary Slater to Skipton,
and from thence was accompanied by John Binns to a general meeting at Crawshawbooth,
where I met with Samuel Fothergill, Margaret Birtwhistle,
afterwards married to Jonathan Raine; and Sarah Routh,
who afterwards married William Taylor.
Next day, in company with the last two, to the quarterly meeting at Lancaster.

Here, in the meeting of ministers,
Margaret Birtwhistle appeared lively and very suitably; but a young man,
and one elder than he, by their public appearances hurt the meeting.

When I reached Whitehaven, I met with Susanna Morris and Elizabeth Morgan,
of Pennsylvania, just landed from Dublin, having visited Ireland.
Susanna Morris was a good old woman, and a sound minister,
whose faith was remarkably tried;
having twice suffered shipwreck on the coast of Ireland, and once, as I have heard,
on the western coast of Europe;
yet was preserved by that power and providence on which she relied,
and her faith was not weakened thereby.

One time it happened in the north of Ireland, and the other time off Dungarvan, when,
as I have been credibly informed, after hanging some hours in the ship`'s shrouds,
apparently in imminent danger of being swept away by the waves every minute,
and the storm continuing so violent, that no boatmen durst venture out to their relief,
a popish priest was made the instrument of her preservation, who,
by his influence and authority, roused some of the inhabitants,
at the risk of their lives to attempt the relief of her and others;
which they providentially effected, and brought her and Joseph Taylor particularly,
safe ashore.

When I landed from Whitehaven at Dublin, I there received a letter from my brother,
informing me that their next province meeting was to be at Limerick next first-day.
Gasret Hassen accompanying me, we left Dublin on fourth-day morning,
and came that evening to Samuel Neale`'s, at Christianstown,
and were next day at the week-day meeting at Rathangan,
and after meeting went to John Ridgway`'s, at Ballycarrol; next day we reached Roscrea,
and Limerick the day following.
At this province meeting I was prevailed on to
stay and join in a visit to friends`' families,
towards which service Garret had before expressed some concern on his mind.
We were accompanied by Joshua Beale, of Cork, John Philips,
George Pease and William Richardson, of Limerick.
It proved a memorable season;
the pure influence of truth having prevailed in the preceding province meeting,
had so prepared friends`' minds, that we found in general, great openness,
and in some families scarcely a dry eye.
No hardness, that I remember, appeared, except in one family;
and the head of that family being an eager pursuer of the world,
in sometime after failed, considerably in debt.
From thence I came directly home to Cork.

On the whole of this long journey, and my third with a certificate,
I have this observation to make: in my two first journeys being much among tender,
religious friends, my labour was easy and edifying,
and I often had great consolation and divine satisfaction among them; but in this last,
coming to many places that were poor and flat, as to the life of religion,
and where other things more prevailed, I often had suffering seasons,
and came off but poorly.

The next summer after my return,
I removed from Cork--leaving my brother John
Gough there in my place--into Leinster province,
and settled near Mountmelick.

I have good reason to believe that I followed right direction,
and the gracious call of divine goodness in this removal, on divers accounts,
as in the good hand of God, the author of all good,
it proved a blessing both to my wife and myself.
There lived hereaway at that time, divers valuable, spiritually minded friends,
through whose tender regard, counsel and help, we gained fresh good,
and to whom we felt great nearness of heart and dear affection,
in the pure love of the one eternal Spirit.

Here I tried something of the linen business,
but found myself so unfit for dealing with the common people, that I saw,
notwithstanding the kind assistance of some friends,
I was not likely to gain any thing by following this business.
And as I had little else at present for a livelihood,
it sometimes spread a dejection over my mind.
Such dispensations are humbling, deeply exercising our faith and patience,
and proving our foundation and our confidence in divine protection,
and reliance on heavenly help.
They are what we generally call trials; and so they are;
but when we consider that the earth is the Lord`'s and the fulness thereof,
and that the cattle of a thousand hills are his;
are not his favours trials as well as his chastisements?
Affluence appears to me a trial, as well as discouraging outward prospects;
but a trial of a different nature, that is,
of our fidelity as stewards of the mercies of God,
to whom we are all to be accountable for the
discharge of the trust he hath invested us with,
that we consume them not upon our lusts, as if that was our own,
which is given us to do good with, and be helpful to others who may stand in need.
As the sunshine of prosperity is apt to lift men up too
high into a state of inconsiderateness and dissipation,
I have thought it a trial, whereby we are under greater danger and temptation;
and have a greater cross to take up to be what we ought to be, than in humbler stations.
It has not fallen to my lot to be much proved with trials of this kind,
and I am led to believe that divine wisdom, who orders all things well,
knew best what was best for me.

For when prospects of things were pleasing, I was prone to be too much elevated,
and therefore needed to be brought and kept low; but in the midst of my discouragement,
a door of hope often opened to me,
from the internal evidence and persuasion of being in my right place,
and of faith that all things would work together for good,
if we were preserved through all to love and fear the Lord;
and so I humbly trust it proved.
My wife being brought low in her mind under the like discouragement,
it proved in the hand of God a good step to her,
to the more certain enjoyment of his blessed presence,
and the comforts of his good Spirit.
She meeting with the like precious visitation here, as I had before in Bristol,
it made us partakers together of the sweet sense
of the gracious regard of him that is above all,
and closely linked us together in true unity, and deep thankfulness,
which often raised in us, to our unspeakable joy, the cheering hope of a dwelling-place,
with the sanctified of the Lord in the regions of bliss.
May I never forget such seasons of unmerited mercy and goodness.

In the spring of the next year,
my mind was again drawn to visit some parts of Cumberland and Westmoreland.
John Pim of Lackah and his wife, offered me their eldest son Moses for a companion,
whom I accepted.
We met at his brother-in-law, Samuel Neale`'s, at Christians-town.
Thence we went next day some miles out of our way to see our dear friend Mary Peisley,
being at that time in affliction.

She had been a gay young woman, but in her youthful years of her gayety,
she was favoured with a powerful and prevailing visitation of divine love,
and giving up faithfully to the heavenly vision,
she became a vessel of honour in the Master`'s house, receiving a gift in the ministry,
and being reverently, watchfully and livingly exercised therein,
to the edification of friends where her lot was cast,
she was indeed an useful member and a shining ornament to the church.

I am ready to conclude, that no one in our day,
from the time of this the effectual visitation of Christ to her soul,
adhered with more steadiness to his guidance, through a variety of probations.
She was, during most part of her time, a member of the same monthly meeting with myself.
Often were we together in public meetings; often on family visits.
She visited friends in England, Ireland and North America, pretty generally;
and soon after her return from her last journey, married our friend Samuel Neale,
and in a few days after departed this life.
I attended both at her marriage and her funeral,
and am satisfied that she is gone to enjoy forever the reward of a well-spent life,
very much devoted to the service of God, and the promotion of truth upon earth.

After this visit of friendship, we got to Dublin on seventh-day evening,
and there on inquiry I was informed, at several places,
that the whole fleet of Whitehaven ships had gone off that day;
but in my return from the quay, accompanied by my kind landlord Thomas Strangman,
I met a man, who told us there was one prevented from getting off.
So I stayed the two meetings in Dublin the next day,
and had a satisfactory time with my dear friends there.
After dinner on second-day we embarked, and on third-day about noon landed at Whitehaven.
That afternoon I went to John Harris`'s, and next morning set off with him and his wife,
a valuable minister, to the quarterly meeting at Carlisle.

One thing appeared to me pleasingly remarkable at that time.
By reason of wet weather, people there were backward at their country work,
and then very busy,
yet several of the men put forward their wives to go to the quarterly meeting,
as they intended themselves to the northern yearly
meeting to be at Kendal about two weeks from that time.
We were that day pretty many in company, but more women than men,
though both the roads and the weather were but indifferent.
Hence I concluded that no other motive but that of religious desire drew them from home.
It affected my mind, and made me hope for a good meeting.
The widow of our worthy friend Robert Atkinson, then about eighty years of age,
with two other elderly women walked on foot eight miles to it.

On fifth-day the quarterly meeting began, and on sixth-day ended,
and was a large and good meeting.
On seventh-day I reached Kendal, and visited meetings thereaway till the yearly meeting;
and after it, spent a few days thereabout, took leave of my poor mother,
and never saw either the place of my nativity or her any more.
She lived only about two or three years after this,
and was favoured in her latter days with peace and quiet;
which was mercifully continued to her end.

This journey began well, like all my others; but, alas, it did not so continue and end,
for want of my steadily adhering to the all-wise Guide in my whole conduct.
Yet I received instruction from it, and learned to exercise more care in some things,
wherein I saw I had missed my way,

I embarked at Whitehaven for Dublin; but we were driven to the north,
and put into Carlingford, about fifty miles from Dublin.
The passengers were three men and three women, and this being a poor place,
we could only get two mean, wretched horses,
on which we helped the women by turns to Dundalk, about eight or ten miles.
From Dundalk we hired three horses, which carried double to Drogheda, where we lodged.
Here no horses were to be met with.
So meeting with a return chaise, I agreed for the three women to go in it,
and myself setting forward on foot in company with one of the passengers,
I arrived in Dublin in good time, and was at the half-year`'s meeting there,
which was a satisfactory season.

Seeing little or no prospect of getting any thing by the linen business,
one morning Thomas Boake, schoolmaster of Mountmelick came to acquaint me,
that the doctor had told him he must quit the school or lose his life,
being then in a bad state of health, and to advise with me and others thereupon.
He soon quitted it, and I succeeded him in a school poor indeed,
as I found it at my first entering upon it;
for except a few friends whose children I had, who duly paid me,
most of the rest put me off with promises, few of which were ever performed;
so that a dull prospect still threatened,
and looking back in my mind to both Bristol and Cork,
I thought it a strange condition to which I was now reduced;
yet hope in the Lord supported me and cheered my mind;
and it was not long before things began to wear a better face;
for some friends of Dublin,
and afterwards others from other parts sent their sons to board with us,
till we had above twenty boys boarded in our house, for whom we were well and duly paid.

About ten years after our marriage, my wife was delivered of a son, whom we named John,
and in a few days after, she departed this life.
For about two years before her decease she had been
engaged a little in the work of the ministry;
but her principal service was in friends`' families, and in the women`'s meetings,
in which her service was much missed when she was removed.
She died in a sweet frame of mind, and in near unity with good friends.

My brother had married at Youghal, a relation of my wife`'s, upon whose death,
he and his wife came into my house at my desire;
and in the winter following I visited Ulster province pretty fully and thoroughly,
being at some meetings twice over.
In this journey I was favoured with the company of old Robert Richardson many miles,
and to many meetings, in severe weather, and he about eighty-four years of age.

I had a particular concern to have a meeting in the town of Belfast:
I consulted Robert upon it; but he did not encourage it,
not one of our profession living in that town:
he said he had been at sundry meetings there, but few of them proved to satisfaction.
So I left the matter for some days; but the concern followed me still.
And it opened in my mind, that if I would have the bread of life to my soul,
I must go to the place appointed for me to receive it, viz: to Belfast.

I thereupon consulted several other friends, all of whom approved of it.
Upon application, the town hall was obtained for it,
and fitted up with seats of deal boards.
Some friends attended from the meetings of Ballinderry, Lisburn,
Hillsborough and Newtown, particularly from Lisburn several friends accompanied me,
and old Robert could not be easy without coming along in the rear of the company;
he sat next to me on the justices`' bench.

The magistrates were so favourable as to order the constables to stand at the door,
to keep out the rabble; the inhabitants of the town of the upper rank,
with their wives and children, came to it in a decent, solid manner.

I had had a great weight and fear on my mind respecting the undertaking;
but proceeding on the foundation hinted above,
a steady hope and reverent dependence on the Almighty stayed my mind,
and I thought my friends felt for me, and felt unity of heart with me.
The meeting was eminently favoured with the clear light of the gospel,
and the sweet sense and enjoyment of divine life and goodness.
After the meeting, Robert, in a tender, thankful frame of mind,
expressed his satisfaction, as did divers other friends.
It proved a good day, honourable to the cause of truth, and affording solid joy to us,
who attended the meeting, which had been crowned with the Divine presence.

After this, I had meetings of the like kind at Dungannon, Moira,
and Legicurry or Richhill, all of them open and comfortable.
And indeed, in this visit to Ulster province,
I was favoured often with the supporting evidence of being under right direction.
It had been on my mind for some years before,
and I thought I had waited till the right time.

I was accompanied in this journey many miles and to many meetings,
by my esteemed friend Thomas Greer, whose company was truly acceptable;
also by my dear friend, Susanna Hatton,
to such meetings as she could get out conveniently to attend.

Sometime after I also visited Munster province, accompanied by my friend John Pim,
of Lackah.

About this time the Methodists had got some footing in sundry parts of Ireland,
and in Mountmelick in particular.
John Curtis, a friend of Bristol, who had been one of them about a year,
having been afterwards convinced of our principles, and received a gift of the ministry,
came over upon a religious visit to friends in Ireland,
amongst whom his service was very acceptable.

I was with him at a large meeting in the court-house in Athy,
another in the assembly room at Athlone, and at several others, which were very large.
He appeared in inwardness of mind to attend upon his gift, and follow its leading;
and concluded his service in Ireland with an epistle to friends whom he had visited;
which the national meeting ordered to be printed.

I mention this by reason of what follows.
One afternoon John Wesley made his first entrance into Mountmelick,
attended by a large company, on horseback, of those who joined him in society.
As several of their ministers had been here before, some of whom had invited me to come,
and bring my family, to hear them preach the gospel,
I had not as yet found freedom to go;
but hearing that John Wesley was to preach that evening in the open market-place,
I was not easy to avoid going.
So I went, and standing at a friend`'s shop-door,
I heard him begin with the following preamble or introduction:
"`Before I unfold to you the oracles of God,
I must first remove a stumbling block out of the way, which is this;
I understand one John Curtis, from Bristol, hath of late been travelling in these parts,
and endeavouring to lay waste that good work which it
hath pleased God to carry on by our hands,
giving out that he was formerly a Methodist and acquainted with me.
Now he never was a Methodist to my knowledge,
and I think he could not be one in or about Bristol without it;
and as to any acquaintance with the said John Curtis, I solemnly declare I never had any;
only I remember being twice in his company occasionally, about eight years ago.
I hope no man will account me an offender for speaking the truth.
If George Fox were here he would embrace me for it.`"

This was the substance of his introduction, in the same words, or very nearly the same,
in which he delivered it, for I gave good attention to this part.
Then he proceeded to what he called unfolding the oracles of God,
which I thought was stamping the matter far too high.

That evening I got two friends to accompany me to his lodging to speak to him hereupon.
At the first mentioning of the subject he discovered some warmth.
"`I tell you, John Curtis has done more harm in his journey through these parts,
than ever he will do good as long as he lives.
He has gone about scattering poison.`"
This high charge he undertook to prove thus: "`What poison is to the body,
that bigotry is to the mind; but John Curtis has been industrious to sow bigotry,
that is, to sow disaffection in the hearts of Christians toward one another,
barely on account of difference in opinion.`"

To all this, I replied to the following import:
I was an entire stranger to John Curtis till he came into these parts, since which,
I had made use of the opportunity of contracting an acquaintance with him;
and being pretty much in his company,
I have known him to be influenced with the universal love of God,
and that he has endeavoured to propagate the same in others.
This thou canst never call scattering poison; and if my account differ from thine,
so doth the foundation on which it is built.
For thine is only upon hearsay,
which is too slender a foundation whereupon publicly to asperse any man`'s character,
who is not present to answer and vindicate himself.
At this he seemed somewhat confused,
and acknowledged that he had not duly considered that part of the matter;
but thought he might depend on the repeated
informations he had received from different quarters.

I further observed to him, that he ought to have duly regarded our Lord`'s directions,
not to judge, etc.
For if any good is done, it is the Lord that doth it,
and in what way and by what instruments he pleases;
and therefore all the glory of it is due to him alone,
and no part of that glory or honour to any instrument, which can do nothing of itself;
and that it would be a sin in any instrument to take to itself what was due to God only:
and that if John Curtis faithfully did what the Lord directed, he would be accepted,
though no shining outward effects should arise from it.

In regard to what thou hast alledged,
of his sowing disaffection in the hearts of Christians, towards one another,
barely on account of difference in opinion; something occurs to me on that head,
which is, that John Curtis might be endued with a sense of the danger,
which some might be in, of magnifying and extolling certain men,
instead of giving all the glory to God,
and apprehend it to be his duty to caution and guard them against that danger,
which might be misconstrued by some,
as seeking to sow disaffection toward those men and their adherents, or to this effect.

This opportunity concluded peaceably, with John Wesley`'s acknowledging,
that it had been to his edification,
and that he therefore wished he could get the like
opportunities with our friends more frequently;
that he saw some things in a clearer light than he had done before,
and that he would never say any thing against John Curtis publicly again,
unless he administered a real foundation for it.
I heard he had the day before made the same preamble, or to the same purport,
before his sermon at Edenderry, and would probably have gone on so from place to place.

I wrote to John Curtis hereupon, who answered, that he never pretended to,
nor ever spoke of his having any intimate acquaintance with John Wesley;
but that he was regularly a Methodist for some time, he sent me a certificate,
signed by several of the same fraternity, and some other testimonials.

Hereupon he wrote to John Wesley,
and sent me over copies of the letters that passed between them.
I did not see that this paper war, if continued,
would be likely to serve any good purpose, and so I wrote to him, and it dropped.
All the use I made of the above-said testimonials,
was occasionally to show them to some of the Methodists, and to one of their ministers.

I was glad to see some in that part awakened out of their sleep of darkness,
to a thoughtfulness about their souls,
and sincerely wished the increase and promotion of solid piety;
but I had opportunity to observe there,
that those who were innocent and well-minded before,
have continued the most steady and circumspect in their conduct;
that those who had before gone into gross pollutions,
being induced to believe that regeneration was an instantaneous, not a gradual work,
did not sufficiently remain under repentance, to let it have its perfect work;
and that instead of pressing forward after the perfection of the inward life,
denying self, and a conformity to this world in its corruptions,
in language and practice, their zeal too much settled in the frequency of their meetings,
hearing sermons, praying, singing, reading,
and treasuring up Scripture texts and passages in their memories,
talking them over too lightly and customarily in conversation,
which rendered these divine truths like salt without the proper savour,
taking from them the awful weight and dignity due to them.

By these means Christian fortitude,
for standing steadfast in reverent simplicity and holy vigilance soon declined;
a silent dependence on Christ, the true teacher, was irksome,
and that dependence which was due to him misplaced on fallible men.
The consequence was a dwindling, a blast on the first buddings of heavenly desires,
a decay of the divine life; and many of them soon returned, like the sow that was washed,
to wallow in the mire and filth of transgression again; and threw off the affectation,
the insipid, and surfeiting talk of religion; the form of godliness,
which they had too much gloried in,
for want of humbly abiding under the purifying power thereof.

Sometime after this, a vacancy falling out in the city of Dublin,
by the death of John Beetham, friends`' schoolmaster there,
and the return to England of George Routh, who had tried the place after him,
my brother being encouraged by friends there to take the charge of that school,
seemed inclined thereto, and as the prospect was promising,
I freely assented to his removal,
although thereby I was left singly to undergo the
labour and care of a large family of boarders,
in which he and his wife had been useful assistants since the death of my wife.
Thinking it best to change my situation, I accordingly married Elizabeth Barnes,
daughter of Thomas Barnes, of Waterford.
About two weeks after our marriage,
we went together to the summer half-year`'s meeting in Dublin.
In our way we spent the first-day among our friends at Timahoe,
it being the last meeting there to many of them.
For in a few days after,
several of their families came to Dublin to embark for North Carolina,
to settle upon my cousin Arthur Dobbs`' lands there, who was their landlord at Timahoe,
and who, upon my application, had offered to me for life,
and after it to my son John and his heirs, one thousand acres of that land.
Robert Millhouse, of Timahoe, was to choose land next to that which himself should take,
but the captain of the ship in which they went, not being well acquainted with the coast,
ran too far to the southward, landed them at Charleston in South Carolina,
and thereupon they settled in that province,
so I was disappointed in my expectation of getting the land taken up by him.
Two other opportunities afterwards presented some probability of getting it taken up;
but by various accidents, my hopes were again disappointed:
may all disappointments of this kind incite to a
greater diligence in seeking the one thing needful,
that good part, which shall never be taken away.

We resided about ten years after our marriage in Mountmelick;
during which time an increasing private family,
and the necessary attendance on my house and school,
prevented my going any great journey; but I attended monthly, province,
and national meetings generally, in which I was often favoured among my brethren,
with the fresh arisings of life, and the renewing of inward strength.

My wife being of a very weakly and tender constitution,
I apprehended the fatigue and burdensome care of a boarding-school,
a load too heavy for her, and from hence conceived a desire,
with submission to the ordering of divine Providence,
of a place where the weight might rest more upon my shoulders, and less on hers;
and having made previous application, I received an invitation to return to Bristol,
and resume the school there.

Hereupon, after some time, I threw up my school in Mountmelick,
attended the fifth month national meeting at Dublin,
after which I embarked there with three friends more,
to attend the yearly meeting at London.
We went aboard ship on fifth-day morning, and landed at Parkgate next morning,
and had an evening meeting at Liverpool.
On seventh-day went to Warrington; on first-day morning,
to the general meeting at Frandley in Cheshire.
On second-day we reached Birmingham; after meeting there on third-day we went to Coventry.
On fourth-day, after a meeting at Coventry, we reached Towcester, and London the next day.
After the yearly meeting was over, Isaac Jackson returned home;
Joshua Wilson stayed a little time amongst his relations; and Joseph Inman and I,
accompanied by our kind landlord, John Eliott of London,
on third-day came to an evening meeting at Reading, appointed to begin at the sixth hour.
Next morning Joseph Inman and I were at the monthly meeting at Newberry,
and that evening at a small meeting at Marlborough;
on fifth-day we came to a meeting at Calne, and after it, to John Fry`'s at Sutton-benjar.
Next day, after meeting there, to Bath, and on seventh-day to Bristol,
where we stayed till sixth-day morning, when leaving Bristol,
we crossed the new passage into Wales; that night came to Cardiff,
and the next to Swanzey, where we stayed over the first-day;
and on a second-day were at an evening meeting at Carmarthen.
On third-day at Llandewybrevy.
On fourth-day, by way of Llaneedless,
we reached John Goodwin`'s. At Llaneedless we went to see a friend`'s widow.
We found her spinning in her poor habitation, and she seemed rejoiced to see us,
and as we had no guide, she readily offered herself for a guide to John Goodwin`'s,
which they called five miles; but it took us near three hours riding.

On fifth-day, after meeting at this ancient, worthy friend`'s house,
we went to his son-in-law, Humphrey Owen`'s, on the seaside,
who had married John`'s eldest daughter; on sixth-day, after meeting,
said Humphrey accompanied us to his brother Lewis Owen`'s, near Dolgelly,
in Merionethshire; and next day along a mountainous road, to Carnarvan, where we stayed,
and had a meeting by ourselves, and after dinner came to Holyhead, on first-day evening.
On second-day morning about two o`'clock, our kind friend saw us on the packet-boat,
and then took leave of us.

On third-day in the evening we landed in Dublin,
and next evening I got safe home to my wife and children in Mountmelick.

After my return I attended the quarterly meeting for Munster, at Clonmel,
and that for Leinster at Enniscorthy,
and then I got my large family ready for our removal,
consisting of my wife and her mother, in her eightieth year, eight children,
and a nurse to the youngest, about eight months old.
With the assistance of sundry kind friends, particularly Thomas Strangman,
of Mountmelick, we all got well to Waterford, and from thence,
after staying about ten days with our friends there, to Bristol.

Now leaving Ireland, after having sojourned there about twenty-four years,
and received much affection and kindness from many friends,
of which I hope to retain the grateful remembrance as long as my memory shall continue,
let me review the state of our Society there, during that space of time.

At my first going thither, there were yet living in most parts of the nation,
where meetings were settled, some of the good old stock, both ministers and elders,
who loved God and mankind, and were esteemed and beloved by them,
being kind and open-hearted,
as well as faithful and circumspect in all the branches of our Christian testimony,
closely united in tender love one with another, in supporting it,
and keeping things in good order in the church.
Their pious care herein was like a fence about the flock,
which kept them together in near unity and greater safety;
so that the young people in most parts,
were generally trained up in innocence of manners, and in plainness of habit and speech.

Some indeed, chiefly of the young men grown up, had for some time past,
refused submission to the good order established;
but I lived there long enough to see the unhappy consequences thereof,
both to many of themselves, and to the body whereof they were members.
Though their tables abounded with elegant dishes, and a variety of liquors;
though they made a figure, and were envied or caressed for a time;
yet most of them were either cut short by death, or fell into disgrace.
The hand of the Lord seemed to be against these
introducers and spreaders of corrupt liberty;
and they never attained that true honour and peace,
which attended the worthy men and women above hinted at,
to whom the first departure of such was matter of great concern and anxiety,
from a clear foresight of the hurtful consequences thereof;
and much labour and pains they took to put a stop to it,
and prevent the spreading thereof, particularly in the city of Cork,
and therefore they were clear of it.

But though some of these were too large for the girdle of truth, to meet about them,
or to be limited by the desires of their best friends;
yet I found the discipline of the church better maintained,
during my first years in Cork, than before them in Bristol; tending to edification,
brotherly comfort and love, and mutual encouragement in piety and virtue,
with a joint desire and care to preserve a uniform regularity,
and to revive and maintain a religious fervency toward God.

Some friends from the several parts attended their province meetings,
which were held regularly once in six weeks, and circulated from one part to another,
yet were most frequently held in Cork.
Those meetings were often sweetly favoured, through the coming together of sincere,
lively spirited friends.
At one of these meetings in particular, in Cork,
soon after my coming to it we had the company of John Duckett, from Leinster,
a worthy elder.
In the men`'s meeting he spoke to us with such divine authority and sweetness,
that to me his words seemed fitly spoken indeed, and,
"`like apples of gold in pictures of silver.`"

The half year`'s meetings in Dublin were attended
by some friends from most parts of the nation.
Here, in the meetings for discipline, as well as for worship,
a zeal for the honour of God, and the good of the church presided,
and friends were incited to keep all things in proper order in the church.
The first time I attended a half year`'s meeting, was in the winter, 1742,
and it was indeed a lively, good meeting, which I hope never to forget.
After I removed from Cork to Mountmelick,
I attended the national and provincial meetings for Leinster pretty constantly,
and often in them was affected with reverent gratitude to the Almighty,
who by the discoveries of divine wisdom,
instituted them for the support and edification of the church,
and in them frequently owned the gatherings of his people in his name,
by the evident manifestation of his divine presence.

In process of time, these worthy men and women,
in whose hearts the love of God and of his people, had, by long growth,
become deeply rooted, one after another, finished their course honourably,
leaving an excellent savour behind them; but when they were removed,
very few of the youth or others, succeeded them in the right line,
to fill up their vacant places with propriety.
Of their survivors, on one hand,
a considerable number retained the ancient plainness of language and habit,
and were rigidly censorious of any deviation therefrom, and valued themselves thereupon,
as if it were the only test and badge of discipleship,
while their hearts were gone after their covetousness, in eagerly pursuing,
and sordidly hoarding temporal wealth.
On the other hand, was a large body of youth and others, shooting up in self-indulgence,
in conformity to the world, and rushing headlong into the temptations of the times.
Yet amidst this inundation of negligence and revolt, there remain in most places,
a number of sincere-hearted friends, a few worthy ministers and elders;
but within these twenty years past, there has been a great alteration for the worse.

The proposals which friends of Bristol made me,
appeared sufficiently encouraging to promise a pretty easy situation as to temporals;
and when in Mountmelick,
this city was presented to my view for a residence for me and my family,
it was brought to my remembrance, how in my young years,
it was made to me what Bethel was to Jacob in his youthful time, when he travelled alone,
with his staff, obeying the command of his parents; that is,
the place where the Lord first visited me with his power and High,
and was a father to me, when I was, as it were, alone,
and far from my parents and all my relations.
After many years, and a great increase of family,
he called Jacob to go up again to Bethel and dwell there, and erect an altar to his God;
and thereupon Jacob obliged his household to put away their strange gods, to be clean,
and change their garments; and so they went.
Under this view,
I hoped this removal might be attended with beneficial effects to me and mine,
and that I had in degree, concurrence therein,
being favoured of the Lord among my dear friends in Ireland, in taking leave of them.

But promised happiness in this life,
often proves a phantom that flies from us as we pursue;
we often think we have it in prospect, but it still keeps beyond our reach:
they who would attain certain and durable happiness,
should extend their views beyond this life.

For, notwithstanding the apparent encouraging prospect, after a while I found things,
both provisions and labour, so much dearer here than in Ireland,
that discouragements and embarrassments crowded upon me to that degree,
that I was often brought very low, under the gloomy prospect,
and my faith was put to a severe trial;
yet it pleased kind Providence to make way for me, and raise my relief in his own time,
for which I desire to be ever gratefully thankful,
and unreservedly dedicated in heart to his service, whose mercies fail not.

I found also a change in another respect, not agreeable to the natural disposition.
He who had visited my soul, and called me into the ministry,
had given me a great place in the particular and near regard,
affection and esteem of friends in Ireland, where I had an open door,
and was often much enlarged in gospel love.
Mostly attending the province meetings in Leinster, friends were rejoiced to see me,
and apt to think me much missed, if at any time I did not get out to any of them.
Whenever I did, I met such a welcome reception amongst friends,
being often opened to their edification,
and to our mutual endearment to each other in the sweet streams of divine life,
and such ready attendance and kindness as were very pleasing to nature.

But coming from thence to Bristol, where I was now become a stranger to many,
and where they were full fed as to vocal ministry, I was here very much shut up,
and for a season seemed to have lost the caresses, cordial invitations,
and that place I had amongst friends in Ireland; which, however,
though in my present trying circumstances, a seemingly additional discouragement,
was not an unprofitable dispensation; for though it was the great favour of the Almighty,
whereby I was opened among my friends to their edification,
and their hearts opened towards me; yet herein the enemy artfully laid his snares,
and often prevailed over my unwatchful soul, to my inward hurt.
For what are all the caresses of mankind?
Of small value in themselves, and often injurious to them whom they please,
conveying hidden poison to the unguarded mind;
while that which alone will stand us in real stead, and be of infinite advantage,
is to get and keep the favour of the Almighty; may I therefore want, and even reject,
whatever would please and nourish that spirit,
which ought to come under daily mortification.

The inward near unity, sympathy, esteem and affection of friends and brethren,
is a very grateful and pleasing enjoyment;
but it may be proper and good for us to be tried and proved,
with being stripped of every leaning stock, but the only sure foundation,
that we may thereby be driven to have recourse to it,
and keep our only safe habitation there.
May this, after a life so tossed up and down, as mine has been,
at length become my case on any terms; and if it be,
it will be more than worth all I have yet suffered, were it many times more;
for all else will be soon over, but this will never end.
