== Supplement to the Journal

Thus far my deceased brother proceeded in the
narrative of the transactions of his own life.
I find by the papers in my hands, that, as noted in the preface,
he drew up a review thereof, at sundry periods,
and commenced the last in the sixty-sixth year of his age; which, it is probably,
had he lived to finish it, would have exhibited, in a continued narration,
the succeeding occurrences of his life, to near the present time;
but he proceeded only a little way in the last review;
and the former in his fifty-fourth year, terminates here.
I regret the want of this continuation by that hand,
which only could give it with those interesting reflections,
resulting from a recollection of the feelings
attending the successive occurrences of his life.
This is an advantage that no other hand can supply;
but as I have in my hands the abstracts of succeeding journeys, and sundry other papers,
I shall endeavour to supply the deficiency to the best of my ability.

After his settling in Bristol, he seems to have been pretty much engaged in his outward,
confining occupation, for the support of himself and a large family,
so as to travel little abroad in the service of truth,
except in short excursions to the neighbouring meetings,
and other services in the vicinage of that city; and to the yearly meeting in London,
which he attended constantly for several years, and where his service was, I believe,
generally acceptable.
It was here for the first time after his removal to Bristol,
and several years separation, I had the satisfaction to meet with him,
which was no inconsiderable addition to the comfort and edification I was favoured with,
in the attendance of that meeting in 1771.
And being mostly with him at meetings and elsewhere,
I had the agreeable opportunity of observing, that the spirit of universal love,
which characterized him in a peculiar manner, procured him the like open reception there,
as formerly amongst his friends in Ireland;
and that the liveliness which still accompanied his public ministry,
procured him also an open door for the reception of his labour and service therein.

During this interval, in the year 1769,
he met with a close trial in the death of his deservedly beloved son John;
a young man of amiable manners, and valuable qualities beyond most of his years,
being blessed with a good natural disposition and capacity,
well improved in his minority, by a diligent application to useful learning,
under the tuition of his father and preceptor; to whom the easy task of instructing him,
his assiduity and ready proficiency conveyed secret joy,
and pleasing hopes of future satisfaction in a son,
who gave such promising tokens of making a useful and
honourable member of religious and civil society.
Nor were these hopes frustrated in the advancing stages of his short life.
For as he grew up, being favoured with solid religious impressions, he sought after,
and attained best wisdom to a degree, in general, exceeding his age.
In his entrance on the stage of life, a propriety and steadiness of deportment,
that might adorn advanced years,
attracted the notice and respectful regard of the best friends,
who had the opportunity of observing, or being acquainted with him.
By a conscientious discharge of every social and religious duty, as a dutiful son,
as an affectionate brother, as an exemplary pattern of plainness,
sobriety and circumspection of life, he gave evident indications,
that he was early acquainted with the grace and truth, which came by Jesus Christ.

I apprehend he was for a season, an assistant to his father in his school;
but the weight of care and embarrassment of this occupation,
not suiting the present temper of his mind,
discouraged him from continuing in that line of life; and therefore,
meeting with an offer from a friend in London,
to assist him in his business in the capacity of a clerk, he removed thither;
and there he laid down the body in or about the twenty-first year of his age,
as I recollect, having in this station, as well as every other,
conducted himself with fidelity, reputation and honour:
in testimony whereof I have an extract of a letter from his employer to his father,
communicated in one from the latter, of tenth month 26th, 1769, as follows, viz:

[.embedded-content-document.letter]
--

"`I now doubt of my eldest son John`'s being any longer in this world;
he was seized with a violent fever last first-day week.
B+++.+++ R., in last seventh-day`'s letter, writes, '`For my own part,
I do not much expect his recovery, which is a great affliction to me on divers accounts;
yet I hope to be resigned to the will of Providence, being well assured,
if he be removed, it will be to his eternal gain,
although my very great loss as well as thine, and many others,
by whom he is dearly beloved.
Oh! that my life, and that of all that know him, may be like his,
that at our death we may say as he did to my wife; '`I have done all that I had to do,
and must now go home.`'`"

--

[.offset]
Soon after he died;
and in my brother`'s next letter he writes me the following account of his funeral.

[.embedded-content-document.letter]
--

"`My son John`'s funeral was uncommonly remarkable.
It was taken to the new meetinghouse at Park, in Southwark.
The meeting was excessively crowded, and many without doors.
It was attended by several public friends,
many friends from several meetings in the city, and many out of the country,
from the love they bore him; the opportunity by all accounts was eminently favoured,
the service thereof, falling to the lot of our worthy, well qualified friend,
Samuel Fothergill, to the tendering of the hearts of many present.

"`Through divine favour and assistance I freely gave him up,
thankful for having such a son, who hath left behind him too few like him in pure,
unmixed goodness, which diligently exerted itself to do well.
He was a most affectionate, dutiful son, both to me and his present mother;
so complete a pattern in every virtue, that I have heard many in London and Bristol say,
that they never saw one of his years like him.
He is happily gone before, safely landed in the port of rest;
and that we may land there is all that we have to desire and be concerned for.`"

--

These short testimonies to the memory of my deceased nephew,
I thought proper to insert here; first, because I am of opinion,
had his father lived to continue his own account of the occurrences of his life so far,
he would not have omitted one so nearly affecting him;
and it was my purpose to notice what I apprehend he would have done, for edification,
as far as I have materials.
Secondly, I thought the delineation of such a character, might be of service,
to some of the youth of this generation, as an example for them to imitate;
as an evidence that early piety may, through divine assistance, be attained,
and that if we seek it in sincerity, and with full purpose of heart,
our search will not be in vain.
"`I love them,`" saith wisdom,
"`that love me, and they that seek me early, shall find me.`"
As an awakening instance of the uncertain tenure of all things in this transitory life;
that all flesh is grass, and the goodliness of man as the flower of the field;
and as a powerful incentive, in consideration thereof,
to extend our views beyond the short-lived glory,
and fading enjoyments of this uncertain world, to the durable riches of righteousness,
and everlasting rewards thereof.
May the rising youth hereby be incited so to number their days,
as that they may apply their hearts to wisdom,
in order to make timely preparation for their final change;
and not suffer themselves to be so far deluded, as to put off this necessary work,
to some future stage of life, which they can have no assurance of attaining to,
reasoning with themselves, through the suggestions of the enemy, that gayety, festivity,
and fleshly liberties, being agreeable to their present age,
may be safely indulged for a season,
as they have much time to repent and grow sober in and that at some more advanced period,
when gravity and seriousness will be more suitable to their years,
they will then apply to those things that belong to peace.
Had this virtuous young man so reasoned, and so acted,
how different had the savour he left behind him been; but O,
how very widely different his condition in his immortal state!

"`If any man will come after me,`" said our blessed Lord,
"`let him take up his cross daily, deny himself, and follow me:`" since then,
these are the prescribed terms of discipleship, and if we would be eternally happy,
are to be submitted to, at one period of our lives or other;
they have greatly the advantage, who are so wise as to submit thereto,
in the early part of life.
It is good for a man that he bear the yoke in his youth,
before his evil propensities be so confirmed by indulgence as to become habitual:
custom has a powerful influence over the human mind,
and the cross to evil habits is hard to endure.
Can the Ethiopian change his skin, or the leopard his spots?
Then may ye also do good, who are accustomed to do evil.`"
On the contrary, as custom also makes hard things easy,
if instead of accustoming ourselves to do evil,
and thereby strengthening our natural propensities thereto,
we accustom our necks to the yoke of Christ,
we shall much sooner feel his yoke become easy, and his burden light;
and early piety is the surest ground of an easy
and peaceful passage through this vale of tears,
as well as laying a good foundation for futurity.
"`Godliness is profitable unto all things, having the promise of the life that now is,
and of that which is to come;`" and those have in a
general way proved most eminently serviceable,
and the brightest lights in their generation,
who have entered early into covenant with their Maker,
and kept the covenant of their youth.

I sincerely desire the youth, into whose hands this may fall,
may deeply ponder these interesting reflections,
so as seriously to consider their latter end, and make timely preparation for it;
as not knowing at what hour the Master may come, at midnight, at cock-crowing,
or the dawning of the day.
And then I am well convinced they would be weaned, not only from the luxury, dissipation,
and gross enormities of the world, but from an affectation of,
and conformity to the vain amusements, manners and fashions thereof,
which many indulge themselves in, to their hurt.
Let them not satisfy themselves with an apprehension,
that they indulge only in things of an indifferent nature,
and in which religion is not concerned;
but instead of unwisely measuring themselves by themselves,
and comparing themselves amongst themselves, bring their deeds to the true criterion,
the light of Christ, that it may be made manifest, what source they originate from;
and in the light many of the little things will
be seen to draw the mind from its proper centre,
and the seats of those that sell doves, occupying the temple of the heart,
to unfit it for an house of prayer.
It is not sufficient that we are preserved from gross evils, although this is laudable,
but if we are concerned to make our calling and election sure,
and to secure an inheritance amongst them that are sanctified,
we are to walk in obedience to the will of God, which is our sanctification,
revealed by his grace in our hearts, which teaches to deny ourselves,
not only of those things that are manifestly evil; but of those also, that,
under the appearance of being indifferent, gratify our carnal desires,
and draw the mind into folly and vanity,
from that state of vigilance on which our safety depends.
We are not only to abstain from those irregularities in conduct,
which injure our reputation with men;
but to keep such a guard upon the avenues of the heart,
that we suffer no thief to find entertainment there,
to steal away our affections from God, or defile this temple of the Holy Ghost.
Man is created but a little lower than the angels,
is designed for higher and nobler pursuits than the gratifications of sense;
and not to rest satisfied in merely avoiding that conduct which exposes him to censure;
but to follow that which merits praise, and procures divine approbation.
"`Finally, brethren, whatsoever things are true, whatsoever things are honest,
whatsoever things are just, whatsoever things are pure, whatsoever things are lovely,
whatsoever things are of good report; if there be any virtue, and if there be any praise,
think on these things.`"

My brother having, now for several years,
been principally engaged in the necessary care and
labour to provide for those of his own household;
in the latter end of the year 1773,
felt a religious concern on his mind to visit friends in some of the counties of England;
and also those of Ireland, in company with Thomas Melhuish, of Taunton, in Somersetshire;
and in order to set himself at liberty to accomplish these visits,
he resigned his school in Bristol.

He soon after entered on the service before him,
in a visit to friends in some of the western and southern counties of England,
and the city of London and its environs; of which visit I received information from him,
in the letters he wrote to me at that time;
the following extracts whereof will best supply what is wanting here.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, 18th of First month, 1774.

I have been now near four months closely employed in visiting friends,
through the four counties of Somerset, Devon, Dorset and Hants;
and sat with friends at many of their monthly meetings,
and the three quarterly meetings for Somersetshire, Dorsetshire, and Hampshire,
all which were large for the season of the year,
and favoured by the Master of our assemblies with that power of love,
which unites his true servants everywhere in a holy concern for the honour of his Name,
and for the faithful support of that testimony he has called them to bear.

I reached this city last first-day morning, having ridden eleven miles before meeting.
I was at Gracious street that morning, at which were Sarah Taylor and Tabitha Marriott,
the former of whom was favoured with a lively opportunity,--it was a good meeting,
and ended well.
I was thankful for having reached it.
In the afternoon I was at Devonshire house; the meeting was very large,
and fresh ability was given to treat with the youth and others,
in the merciful opening of the pure spring of the gospel.
Yesterday I attended the select morning meeting,
and in the afternoon the two weeks`' meeting.
And in the evening, Thomas Corbyn with his lodgers, the friends above-mentioned,
visited at my lodgings, where we had a consolatory time of retirement,
in which our heavenly Father was graciously
pleased to break the bread of life amongst us.
I shall be likely to be three or four weeks in and about London, and when I am clear,
I have the meetings of Berkshire and Wiltshire to visit in my way home.
I desire to be every day where I ought and as I ought, that if I can do no good,
I may be in the way of renewedly receiving some fresh supply from the living fountain,
which refreshes and spiritually unites all the true travellers heavenward,
in daily gratitude to the kind Author of all good.

--

[.asterism]
'''

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, 5th of Second month, 1774.

My dear companion,
who has obtained his credentials from their monthly and quarterly meetings, writes to me,
that he is hastened in his mind to move forward;
but both he and I must submit to bear the curb, and exercise patience.
I am at times assaulted with earnest longings to make haste home,
to get a little time there, before my coming over to visit friends in Ireland;
still I am favoured with the renewing of that gracious help,
which raises over all things,
and gives the single desire of being both where and what I should be.
I entered on this service with an earnest desire,
that I might be both guided and guarded aright;
and hitherto with great thankfulness have to acknowledge,
that my prayers have been answered; and that he who hath the key of David,
hath been graciously pleased many times to open his storehouse,
and from thence to unfold doctrine, counsel, consolation and reproof,
to the differing states of the people.

--

[.asterism]
'''

[.embedded-content-document.letter]
--

[.signed-section-context-open]
London, 1st of Third month, 1774.

I have now been in this city seven first-days`' and seven second-days`' morning meetings,
and through the other parts of those weeks, have besides those of London,
Westminster and Southwark, laboured in sundry meetings around them.
Tomorrow I expect to attend the last two meetings here;
that for worship at Gracious street, in the morning,
and the monthly meeting at Devonshire house, in the afternoon;
next day to set off for Berkshire, Wiltshire and Bristol.
So that it looks likely to be the fourth month before I can set out for Dublin.

I have cause to be humbly thankful to the author of all our mercies,
who hath been kind to me through my winter`'s travels, favouring me with good health,
through all winds and weathers, and with a kind reception everywhere.
At this city, being entered into my proper labour and business,
I have found that I could not retire hence, any sooner than the stay above mentioned,
and I think I shall not overstay my time, but rather otherwise,
having found an enlargement of heart beyond expectation,
and having contributed to increase the morning meeting of elders here,
with a valuable addition thereto,
though I found it hard labour through the diffidence and reluctance of some;
yet the power and love of truth at length prevailed,
to the satisfaction and comfort of many good friends.

--

He got home on the 8th of third month,
and in about a week afterward took a turn to the quarterly meeting of Somersetshire,
at Glastonbury, and that for Wiltshire, at Devizes,
and was at some other meetings in his way from one to the other.

The beginning of fourth month he left home on his intended visit to Ireland;
he came to the quarterly meeting at Worcester, and thence by Birmingham, Coventry,
Dudley and Stourbridge, to Colebrookdale,
where he was at meetings at the New-dale and Old-dale, and visited sundry families,
accompanied by Daniel Rose.

From Colebrookdale, he went by Shrewsbury, to Dolobran,
where the meetinghouse was nearly full,
the meeting began at eight o`'clock in the morning, and was very comfortable.
The next day he got to Llewindee, to William Howell`'s,
son-in-law to the late worthy friend, John Goodwin,
with whom John`'s widow was then living, being eighty-three years of age,
and had a meeting there,
and from thence he went by Llaneedless to the Welsh yearly meeting at Brecknock,
which began on the 26th of fourth month.
The meeting of ministers and elders, began at nine o`'clock in the morning,
and at three in the afternoon, a meeting of friends only; and after it the men`'s meeting,
which held till it was almost dark, and then adjourned to the seventh hour next morning,
when friends met again, and the meeting held till about nine.
At ten the public meeting began in the town-hall,
which was excessively crowded and satisfactory.

This yearly meeting ended the 27th of fourth month,
and the half year`'s meeting in Dublin was to begin the 1st of fifth month.
So he writes; "`William Howell and I came forty-one miles after dinner, to Llaneedless,
where, on the 28th, we had a large meeting in the town-hall or session room,
beginning at eight o`'clock, which was much favoured.
Margaret Jarman and Mary Hunt, accompanied us from thence to Escargoch,
where we also had a memorable opportunity, our hearts being much tendered together.`"
On the 29th, being sixth-day of the week, he set off from Llewindee,
accompanied by Owen Owen, son of Humphrey Owen aforementioned,
and grandson to John Goodwin, for Holyhead, and that day,
although they were detained some hours for the tide to fall,
till they could cross a river in the way, and in crossing which,
they were for a good while up to the saddle skirts, they reached Carnarvan,
being fifty miles, that night,
and Holyhead about eleven o`'clock in the forenoon of seventh-day;
went aboard the packet boat about two o`'clock on first-day morning;
but having little wind, did not get to Dublin till second-day evening,
being the 2nd day of the fifth month, and of the national meeting.

Of his journey in Ireland, he kept a brief diary; but not so particular,
as of the former through Wales,
being only a summary account of the meetings and places he was at each day,
without any remarks on meetings or occurrences to diversify the narration,
and therefore I shall be obliged to comprise the relation thereof in a narrow compass.

He visited the meetings in course; first, by Edenderry, Rathangan and Ballitore,
to the six weeks`' meeting at Carlow, and thence westward, to Ballimurry,
and returned to the quarterly meeting at Edenderry, in concert with his companion,
Thomas Melhuish.
From thence they directed their course towards the province of Munster, by Tullamore,
Birr and Kilconnermore, to Limerick, and from thence through Munster,
finishing their visit to that province, at the province meeting at Waterford;
thence through the county of Wexford, and so into the county of Carlow,
where Thomas Melhuish and he separated, at Castledermot, Thomas`'s draft being to Ulster,
and my brother`'s concern more to the adjacent parts of Leinster.

After parting with Thomas.
Melhuish, he continued visiting friends in these parts,
till the province meeting of Wicklow, after which, and spending some days in Dublin,
he went from thence to the province meeting for Ulster, at Ballinderry,
and returned pretty directly back to Dublin,
without appointing any meeting in that province,
and continued visiting meetings in different parts of Leinster province,
chiefly till the ensuing quarterly meeting, which was held at Enniscorthy,
and from thence proceeded directly to Waterford, to take shipping for Bristol.

This visit took him up near four months,
for he embarked for Bristol on or about the 24th of eighth month,
the greatest part of which time seems to have been employed in Leinster province,
having visited most parts thereof at least twice over.

Having, as aforementioned, resigned his school at Bristol,
in order to be at liberty to discharge what was pointed out to him as a duty;
and his service being now finished,
he was out of employment for the support of himself and family.
The prospect of this in giving up to this service, must, I imagine,
have been a pretty close trial of faith; as he could not, at the time of his resignation,
have any apprehension of the way which afterwards
opened for their employment and subsistence;
but knowing he was faithful who had called him into the service,
he was strengthened to go forth in faith, and a humble dependence on him,
whom he served for support, inwardly and outwardly;
and in due time a way opened for him to his satisfaction.
By my removal from Dublin, where I had resided upwards of twenty-three years, to Lisburn,
which happened during his travels in this nation, the school there became vacant.
Whereupon friends of Dublin made him proposals to undertake the care thereof;
to which he agreed, and soon after his return to Bristol,
removed with his family to settle in that city.

The necessary attendance upon his school,
confined him pretty much to the place of his residence, and parts adjacent,
for the space of two or three years; till about the summer of 1777,
when his family being grown up, and mostly in a way to provide for themselves;
and his youngest son having gotten an agreeable place of apprenticeship,
he found his way open finally to relinquish the
confining and exercising occupation of his school,
in order to be more at liberty in the evening of his day,
to accomplish the remaining part of his day`'s work, against the termination thereof;
and from this time to his removal out of this life,
he was much engaged to travel and labour amongst friends,
in the different quarters of this nation, for the promotion of truth and righteousness.

As he had not visited Ulster province in his late visit to this nation,
the discharging of that debt was the principal service pointed out to him,
in the following manner,
as he himself expresses it in the introduction to his account of said visit:

[.asterism]
'''

Seventh month 1st, 1777.
--A good friend from England lately told us, in a meeting,
that our old copy books were sullied, and too full of blots;
that we should get new books to keep our accounts in, and keep them fair and clean;
and I wished with the Lord`'s assistance to do so, viz:
to have my heart and life made and kept clean.

I felt a longing desire to undergo afresh the '`washing of regeneration,`' in
order to be favoured with '`the renewing of the Holy Ghost.`'
I thought he who said to the blind man, '`Go wash in the pool of Siloam,`' said unto me,
Go to the northern parts of Ireland,
to visit what is left there of the professors of truth;
and therewith infused the new covenant, or solemn engagement on my part,
to give up thereto.
O, poor cold north; almost totally dead as to the divine life!
In visiting thy sons and daughters, I foresee great anxieties, inward conflicts,
and trying baptisms; may I duly mind that part of Christ`'s counsel to his followers;
'`In your patience possess ye your souls;`' and indeed
his whole counsel conveyed through his holy Spirit;
as I have the greatest need closely to attend to it in all things,
and practise faithful obedience thereto.

May I daily watch and pray, and labour, both to open a new book of accounts,
respecting the Lord`'s holy covenant and my walking humbly therein,
and also endeavour to keep it carefully without blot or blemish,
both within in his sight, and without toward mankind; in a daily exercise,
'`to keep always a conscience void of offence, towards God and towards men.`'
May I watch and strive against corrupt self, and keep a diary or daily account thereof,
morning and evening, remembering, '`that to live after the flesh is to die,
but through the spirit to mortify the deeds of the body is to live.`'
Oh, that in me all self were slain, that Christ might live and ever reign in my soul,
who visited, invited, attracted it, about the 22nd year of my age; and has,
through his grace, preserved me through many revolutions,
and often opened a way for me to steer along, when no way, or next to none, appeared,
till now I am come to the sixty-filth year of my life.

17th.--After I awoke this morning, this text sprang in my mind;
'`Christ gave himself for us, that he might redeem us from all iniquity,
and purify unto himself a peculiar people,
zealous of good works;`' with a strong desire that whatever it cost me, whatever labour,
self-denial, or seeming hardship, I may obtain the great end, for which I have a being;
the '`one thing needful,`' which Mary made her choice, and thereby pleased her Lord, viz:
that of being more thoroughly redeemed from every corruption of nature,
or neglect of duty to God.
May I be more purified in heart and life; more inflamed with a holy zeal for his honour,
'`laying aside every weight and burden, and the sin which doth so easily beset,
and run with patience the race that is set before me,
looking unto Jesus the author and finisher of our faith, who,
for the joy that was set before him, endured the cross, despising the shame,
and is set down at the right hand of the throne of God.`'
I am likely soon to set forward as a poor pilgrim,
to the coldest and remotest parts of the north of this nation,
which are rarely visited by any friends in the ministry,
they meet with so much discouragement that way; but I must go and labour amongst them,
according to the ability given, for the working out my salvation,
with fear and trembling.

18th.--Today we had a silent, but to me and some others, I hope an edifying meeting,
under the divine and spiritual ministry of the great Minister of life and salvation,
who therein set before me two services,
the one to procure some subscriptions for the relief of a poor family,
which after meeting I set about and succeeded in.
The other was my journey to the north, with a lively and fresh encouragement thereto,
under the consideration of the uncertainty of our time here,
and that if my duty to God required me to be doing one thing in one place,
and death should arrest me doing something else in another place,
how miserable would my state be.
The covenant of my youth was now brought to my remembrance,
with a lively and affecting impression, in the language adopted by the prophet Jeremiah,
speaking in the name of the Lord; '`I remember thee, the kindness of thy youth;
the love of thine espousals, when thou wentest after me in the wilderness,
in a land that was not sown.
Israel was holiness to the Lord, and the first fruits of his increase.`'
When I first gave up to the heavenly visitation,
how was my heart melted into holy admiration of the love of God,
and of his condescension to my low estate;
pure goodness was then all my desire and delight.
In the intervals of labour I loved to retire from the world, to him my best friend,
who was with me in my labour, instructing and helping me in it,
and making hard things easy, so that '`I walked by faith,
and not by sight,`' my mind being in heaven, often overflowing;
with the effusion of his grace and goodness.
Under this enlivening recollection, an ardent desire was rekindled in my heart,
to renew my covenant, to return to my first love; and do my first works,
in an unreserved resignation, to do the will of God.

My heart was influenced with a wish, that our young people in general,
might be induced to love religious retirement,
in order to become acquainted with the Wonderful Counsellor,
who is more readily met with therein, than in the crowds,
commotions and tumults of the world, and in their own experience prove,
that '`It is good for a man that he bear the yoke in his youth,
he sitteth alone and keepeth silence--he putteth his mouth in the dust,
if so be there may be I hope.`'
May our conversation be in heaven,
and our language and whole demeanour make it manifest that we have been with Jesus.

Eighth month 4th.--I returned from visiting the families of Timahoe meeting,
in company with Joseph Williams,
wherein a divine visitation seemed to be renewedly extended to them;
it is much to be desired, that they may duly embrace it, to come up in their duty,
and to persevere in well doing, to the end of their days.

Such visits among our friends, under divine influence, are of service,
and worthy of being often performed, as tending to renew the bonds of friendship,
in the truth; to provoke to love and good works,
and as they are engaged steadily to wait upon the Lord,
frequently prove seasons of renewing of strength to the visitors, as well as visited.

[.asterism]
'''

Two days after, viz: the 6th of eighth month,
he set forward on his visit to friends of Ulster province,
taking his way by the quarterly meeting for Leinster province, held at Moate;
and after the conclusion thereof, proceeded to Oldcastle, Coothill and Castleshane,
in each of which three meetings he did not only labour
amongst his friends in their public assemblies,
but also visited them in their several families.
From Castleshane he crossed over to Lurgan, and was on first-day at the meeting there,
it being their men`'s and women`'s meeting.
At that meeting I met him, and it was to some an edifying season.
From Lurgan he went to Rathfriland, and visited the families belonging to that meeting.
From thence he came to Lisburn, and had a meeting there, and next day at Hillsborough.

The three succeeding days were the quarterly meeting at Ballinderry, which he attended,
and had acceptable service therein.
The following week he took the meetings of Moyallen, Lurgan, Ballihagan, and Charlemount,
in succession, visited some families,
and was again at the meeting near Charlemount on first-day following, which he observes,
was large, like a province meeting.
He continued his course from thence, to Antrim quarter;
and as the visiting of this quarter was in a particular
manner impressed as a duty upon his mind,
he visited the meetings thereof thoroughly,
and all or most of the families of friends thereaway.
On the first-day he was at Grange, of which he wrote to a friend;
"`We had a kind of general meeting at Grange yesterday, there being at it,
friends from Toberhead, Ballinacree, Clough, Ballymena and Antrim,
and I think it was a time of renewed visitation of divine favour to some.
That we may dedicate the residue of our days to the service of the Lord and his people,
is my sincere desire for us both, and many more.`"

He spent about a week among friends in this quarter.
But, as I recollect, his visit both to said quarter in particular,
and the province in general, was in some degree cut short, by the arrival of our friends,
Thomas Corbyn, John Townsend, and Joseph Roe, from London, John Storer, from Nottingham,
and James Backhouse, from the county of Durham,
who came over in consequence of an appointment of the yearly meeting of London,
to visit the meetings of discipline in this nation.
Which visit they entered upon at the men`'s and women`'s meeting, for that purpose,
appointed at Lisburn the 10th day of ninth month, this year,
while my brother was engaged in the neighbouring part of Antrim quarter.
This induced him to come over to that meeting,
and the said friends being very desirous that he should
be in Dublin at the time of their arrival there,
in the course of their visit, he felt easy to accompany them to Antrim,
and from thence to Lurgan; from whence they proceeded to Charlemount,
to be at the men`'s and women`'s meeting there on first-day, and Ballihagan on second-day.
My brother staying first-day morning meeting at Lurgan,
had also an evening meeting at Lisburn, appointed at the fifth hour,
and next day at Newtown.
Fourthday following,
was with the English friends at the men`'s and women`'s meeting at Lurgan,
and next day came with them to that of Lisburn, held at Ballinderry.
The province meeting at Lurgan succeeded by appointment, on sixth,
seventh and first-days, over which he stayed, and after that,
and having a meeting at Rathfriland, in the market house, one more at Lurgan,
and another at Moyallen, he returned to Dublin.

When he arrived at Dublin, he found Thomas Dobson, from near Carlisle,
who had come over under a particular concern for that service,
engaged in a visit to friends`' families in that city; upon his arrival,
he joined him in the service, and accompanied him to ninety families,
he having visited forty-six before my brother`'s return.

And in about three months after, Matthew Johnson, from Cornwood, in Northumberland,
coming to the aforesaid city, under the like concern,
after discharging himself in the same service to the meetings of Lisburn and Ballinderry,
my brother accompanied him also in his visit to the families of friends there.
Thus he was diligently engaged most part of his latter days,
in almost a continued series of laborious service in the church,
either at home or abroad.

When we reflect upon the repeated visits of this kind,
which divers other friends from distant parts, "`as well as those above mentioned,
from the fresh and lively impressions of duty, have been engaged in,
to friends in the different quarters of this nation; leaving,
or submitting to be detained from every near connection in life,
to labour amongst us in the work of the gospel, not only in public,
but from house to house; and often in the clear opening of our states,
under the influence of truth, even as from man to man,
it should affect every considerate mind with humbling
sensations of thankfulness to our beneficent Creator,
for his unbounded lovingkindness and mercy to us as a people, under the view,
that although many of the professors of truth, one going to his farm,
and another to his merchandize, have slighted repeated calls,
and excused themselves from the necessary preparation
for admittance to the marriage supper,
he hath not yet given charge to his servants, to go to the lanes and highways,
to call in others; but is still causing us to be striven with,
in close and searching labour.
May the serious consideration hereof so impress our minds,
as to produce holy resolution to turn to him that smiteth us, and in reality,
to seek the Lord of Hosts.
Remembering the day of our visitation hath its assigned period,
in the determination of his unsearchable wisdom, who hath declared,
"`my spirit shall not always strive with man, for that he also is flesh.`"

On the 3rd day of ninth month, 1778, he set forward on a journey,
to visit his friends in the province of Munster,
making his way pretty directly through the county of Carlow to Clonmel,
where he commenced his visit to said province, being there on a first-day,
at their two meetings.
On second-day he writes, "`Not suiting for any public meeting hereaway,
being the time of their assizes, we were at nineteen friends`' houses,
and had good opportunities in several of them.`"
So proceeding, he had meetings in course, at the following places, viz: Cashel,
Garryroan, Limerick; Cork on first-day, the two public meetings,
and a third with divers friends in the evening, at Joseph Garratt`'s;
on second-day he went to Bandon, accompanied by several friends, and back to Cork;
was at their meeting on third-day, and after it at the men`'s meeting;
on fourth-day to Youghal, to a meeting appointed at five o`'clock that evening,
stayed their week-day meeting next day, and after it returned to Cork,
to the quarterly meeting.
From thence, by Garryroan and Clonmel, to Waterford, where his visit terminated.
He fell in with the meetings of Forest, county of Wexford, Carlow and Rathangan,
in his way from Waterford to the quarterly meeting for Leinster province,
held at Edenderry, the 4th of tenth month, and from thence returned home.

He continued at and about home for near eleven months,
for just at the same time of the succeeding year, viz: the 2nd of ninth month, 1779,
he left home to go to the quarterly meeting at Edenderry,
and thence by Moate and Ballimurry, he made his way into Ulster province again;
being at Oldcastle on first-day, the 10th of ninth month.
From thence to a meeting at Coothill, which was a large, crowded meeting,
several of the town`'s people, I suppose, coming in.
From Coothill, he came to Castleshane, thence to Moyallen,
and attended the week-day meeting at Lurgan, which he says was a large and good meeting.
The quarterly meeting at Lisburn succeeding, he attended it, and after that,
was at meetings at Rathfriland, Moyallen, Ballihagan, and near Charlemount successively.
At this last meeting he joined in the visit to the families of friends,
and in company with some friends of that meeting, performed the said visit thoroughly,
spending therein near two weeks, although closely engaged day by day.
After this service, he visited the meetings of Antrim quarter,
and the rest of the meetings of the province in course,
finishing his service at the province meeting at Lurgan,
the 29th and 30th of the tenth month.

The next service I find him engaged in,
was a visit to the monthly meetings of Mountmellick and Edenderry; in his letter to me,
dated, first month, 1780, he writes, "`In the very cold weather which we have had,
I visited all the particular meetings of Mountmellick, and Edenderry monthly meetings,
and though I could not but lament the state of many careless professors,
yet I had good satisfaction in discharging my duty therein.`"

In the summer of the same year,
he made another excursion through some parts of Leinster province,
and as far as Waterford.
And about the same season as the two past years, viz:
on or about the 22nd of eighth month, 1780,
he set out again on a visit to friends in the province of Munster.
In his first day`'s journey his guide dropped his saddle-bags,
whereby being deprived of necessary change of linen, etc., for the journey before him,
I was told, it put him to a stand whether to proceed or return home;
and also upon seriously considering the grounds he set out on,
and the validity of his commission, and upon consulting the oracle in his own breast,
it was intimated to him, that he must go forward, if his life went for it.
The first meeting he had, was at Mountmellick, from whence he wrote;
"`We had a good meeting here today, which seemed as a fresh seal to my commission,
and makes me strongly desire I may be preserved, to attend singly to my duty,
and faithfully discharge it.`"
From Mountmellick, he went by Roscrea, Birr, and Kilconnermore, to Limerick,
to the province meeting for Munster, which, by the account he gave,
was said to be the largest that was remembered in that place,
many friends from Leinster attending it;--and further,
"`The kind Father and Author of all our mercies,
favours my mind with the sweet sense of his divine love,
and a desire to follow and serve him,
who is a rich rewarder of all his faithful servants.`"
Here, being requested by friends, to forward the family visit, he consented,
following therein the pointings of duty.
On the fourth-day after the province meeting,
in conjunction with divers friends of that province,
he entered upon this exercising service:
his succeeding labours in this and the following service,
may be best understood from extracts from his own letters, written to his wife,
during his being engaged therein.

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Limerick, 1st of Ninth month, 1780.

On fourth-day, we began the family visit here,
and that day we had six solemn opportunities; visiting so many families,
and yesterday we followed the business closely; having eight solemn meetings,
some of which held long, so that it was near ten at night when the last of them broke up.
We hope that two days more will be sufficient to finish the family visit here,
so after first-day, expect to be thoroughly clear of this part of Munster,
and on second-day to proceed with the friends who stay with me here, to Cork.
To look at the labour in a service of this kind, through such a very large, increasing,
extensive meeting as that of Cork, would appear very weighty, and almost terrifying,
were it not for the earnest, which the great and good Master hath already given us;
who hath led us along, in the sweet enjoyment of his own pure love,
and therein hath united our spirits, and hath opened a door of utterance,
reaching the witness, and tendering the hearts of many.

--

[.asterism]
'''

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Cork, 13th of Ninth month.

It is now somewhat hard for me to get a little time to write,
we are so closely employed from early in the morning till late in the evening.
We were on the service yesterday and today at a little past seven in the morning.
We had nine family meetings on second-day; yesterday, one before meeting, five after,
and today hath been a day of almost incessant labour, having had nine family meetings,
and some of them pretty long,
and some also much favoured with the sweet flow of the heavenly Father`'s love,
tendering the hearts of divers.
Under this divine favour, I have had a strong desire, on the behalf of our children,
that the great Author of pure goodness,
would incline their hearts more and more to their principal interest,
and clothe their minds with the heavenly sense of his love,
and with the humility becoming depending creatures,
and enamour them with the beauty of truth, which will never wax old;
that through its power, they might freely sacrifice to him, what he calls for;
and not look after the temptations and vanities of the world;
but have the eye single to things infinitely more important,
that therein they may be blessed of the Lord, with his favour,
which is better than all things else.

--

[.asterism]
'''

[.embedded-content-document.letter]
--

[.signed-section-context-open]
Ninth month 16th, 1780.

This hath been a day of favour to me and my friends employed in the family visit;
a tender visitation from the Father of mercies, hath been extended to divers families;
particularly one young man, and his wife who was not educated in our Society,
but this day was reduced to tenderness, both she and her husband.
I wish they may retain it, and come in at the right door to be useful and exemplary.
We have followed the work with great diligence,
from early in the morning till late in the evening, having in the course of this week,
visited above fifty families, and two hundred and twenty persons.

--

In his next letter, and the last he wrote, he gives an account of a disorder, viz:
the dysentery, with which many had been seized,
and that it had followed him very closely for several days.
It seems that partly from reserve,
but chiefly from a desire to accomplish the remaining part of the service before him,
so as to get through it in time to return home against the '`ensuing half-year`'s meeting,
he suffered this disorder to gather strength before he let it be known,
to a degree of obstinacy beyond the power of medicine to remove;
for although no care of attendance, or suitable applications,
under the direction of skillful physicians were wanting, yet these proving ineffectual,
he departed out of this transitory state of existence in much tranquillity of mind,
at the house of his kind friend, Joseph Garratt, in Cork,
on the 6th day of the tenth month, 1780, and was buried in friends`' burying ground,
in the suburbs of that city, the 9th of the same month,
his funeral being largely attended by friends and many others,
as I am informed by some friends from thence, one of whom writes;
"`We had a solemn opportunity, the wing of ancient goodness being over the assembly,
in the performance of the last office due to the worthy deceased.`"

Thus it pleased the divine Being, in whose hands our lives are,
to release him from further labour in the church militant,
and remove him from works to rewards, leaving among his surviving friends a good savour;
his removal being generally regretted,
and his memory greatly and extensively respected by most or all that knew him.
Being a man of meekness, humility and universal benevolence;
kindly disposed and affectionate to his friends, and mankind in general,
he in return possessed their affectionate regard and esteem in a general way.

In his spirit, he was preserved bright and living, through his concluding labours,
and to the last period of his life,
by the accounts I received from some of those who were sharers and witnesses thereof.
My respected friend, Samuel Neale, in sympathy with our sorrow,
for the loss of a near and justly beloved relation,
obliged me with an affecting epistle of condolence, in which he expresseth;
"`It is needless to say he is a great loss,
in a society capacity he was fervent and devoted; his lamp was replenished with oil,
and it shined as bright as ever in my judgment--
he finished his course as a faithful soldier;
he finished it, making war in righteousness.
I was with him at Limerick, at our province meeting,
and accompanied him to the families there pretty generally;
he was like an overflowing spring, and freely diffused what he was made partaker of,
amongst his friends and brethren, and all who came in his way.
After which he came to our city, and the same strength, zeal,
and authority attended him here in the public meeting,
and more select opportunities I was at with him.
He was at the labour early and late,
until forced to submit to the increasing infirmity of body.
I think he had finished all to five families, when the great Orderer of all things,
gave him a release from further labour in his militant church.
He was calm and composed in his mind, said he was resigned to the divine will,
and was prepared for the event, relying on the mercy of God.
He was certainly much favoured by a divine qualification, and as the evening approached,
his sun went down bright, which is the crown of all.`"

And although he had his close trials, and discouraging prospects,
in various seasons of his life, as we may gather from the preceding pages,
yet being through all, enabled to stay his mind on the Lord,
he was preserved in peaceful resignation, and safely brought through them;
and was favoured to enjoy the evening of his day, as to secular engagements,
in serenity and calm repose,
in a state of liberty to devote himself more fully to the service of truth,
and to fulfill his ministry to the edification of the churches in this nation.
He lived to see his children well settled in marriage, to his full satisfaction,
or in a way to support themselves reputably,
if favoured with the divine blessing upon their labours,
and preserved in the fear of the Lord,
which he desired for them more than outward riches.
Incited through the gracious visitation of divine goodness to him in his youth,
in the first place, to seek the kingdom of God and his righteousness,
he found the promise verified, that sufficiency of other things were added.
And having been spared to his family,
till his immediate assistance became less necessary for their support,
and to the church till his day`'s work was, in a good degree, well accomplished;
he came to his grave in full age, as a shock of corn cometh in his season,
experiencing the work of righteousness to be peace, and the effect of righteousness,
quietness and assurance forever.
From hence those who may be tried with the like probations,
as this is a world of vicissitude, may receive encouragement in the cloudy season,
in faith and patience, to cast their care on that divine Being, who careth for his own,
and will bring them safely through all difficulties and discouragements,
provided their hearts are sincere toward him,
and all things will work together for good to those that love God.

The end of these publications is not to extol the man,
but to recommend righteousness to mankind,
by pointing out the beneficial and happy effects thereof, in real life;
and as the desire of happiness, planted deep in our nature,
is a universal affection of the human mind,
although often sought in things that cannot give it, or at best,
but the shadowy and deceptive appearance thereof, to incite them,
in imitation of the just, to I seek it where only it is to be found,
in pure religion and virtue, walking in all the commandments of the Lord blameless.
If we have regarded the deceased with affectionate esteem,
and honoured them for their works`' sake,
let our regard for their memory prompt us to the imitation of their good examples.
If we regret their loss, and the vacancy of their places,
let us consider that a measure of the same divine Spirit,
which wrought powerfully in them for their redemption,
and enlivened them to every good word and work, is also given to us individually,
for the effecting of the same happy experience in us, whereby,
through faithful obedience on our parts,
we may receive a qualification to fill up some of the vacant seats,
be serviceable in our respective allotments, exemplary in our lives,
and blessed in our end.
