[#testimony, short="Testimony from Dublin Men's Meeting"]
== A Testimony, from the Men's Meeting of Dublin, concerning James Gough, deceased.

It having pleased divine providence,
to remove from us by death our worthy friend James Gough,
we feel our minds impressed to give forth the following testimony concerning him.

By authentic accounts we find he was born at Kendal in Westmoreland, in the year 1712.
And, in his young years,
was made sensible of an inward monitor to reprove his propensity to evil,
and convince him of the error of his ways, which made, at times,
profitable impressions on his mind for a season.
But, through the instability of youth,
these impressions proved not deep enough to be lasting,
till about the twenty-first year of his age,
when he removed from the north of England to Bristol.
It pleased divine Goodness to favour him with a
fresh and prevailing visitation of his love,
whereby he was made willing to give up, in self-denial and circumspection of life,
to yield obedience to his requirings,
who in his fatherly loving kindness had thus visited his soul;
and by the gradual operation of the divine power therein,
he experienced a growth in the work of sanctification,
and was thereby formed into a vessel prepared for the Master's use.

About the year 1738, he removed from Bristol, and settled in Cork,
and soon after he came forth in a public testimony to
the virtue and efficacy of that truth,
which he himself had experienced the beneficial effects of; and growing in his gift,
he became an able minister of the gospel, and an instrument of service in the church.

His first journey, in the work of the ministry, was in the year 1740,
to the counties of Cumberland, Westmoreland, Lancashire, and part of Yorkshire.
His next to Leinster province; and in the summer of 1743,
he visited the meetings of Friends through the principality of Wales,
and many parts of England; in the course of which visit,
he attended the yearly meeting of Wales, with those of Bristol and London.
Soon after his return he thought it his duty to remove into Leinster province,
and fixed his residence in Mountmelick, where his service became extensive,
being in the centre of a large body of Friends.
He almost constantly attended our province, quarterly and national meetings,
where he was often drawn forth in the pure streams of gospel love, to the refreshment,
and edification of Friends.
In the year 1774, he settled in this city, where he was well received, and well beloved,
his innocent life and conversation adorning his gospel labours amongst us,
being filled with love to mankind in general,
and in particular to the flock and family with
whom he was joined in religious fellowship.

He followed his occupation of schoolmaster for sometime in this city, but,
in his advanced years,
not being sufficiently able to bear the fatigue
and confinement attendant on that employment,
and being desirous to be more at liberty for the exercise of his gift, he gave it up;
and for the last three years of his being a member of this meeting,
travelled much abroad in the different quarters of this nation, visiting the meetings,
and in many places, the families of Friends,
to stir up the pure mind by way of remembrance, and to provoke to love and good works.

Being on a religious visit to Friends in the province of Munster,
and having proceeded to the city of Cork,
where he was engaged in a visit to the families of Friends,
and had with much diligence nearly finished the same,
it pleased the Sovereign Ruler of the universe, in whose hands our lives are,
there to put a period to his labours, and to remove him from works to rewards.
Being seized with indisposition, and following the service before him too closely,
as was apprehended, it increased upon him to such a degree as brought on his dissolution,
and he quietly departed this life, at the house of our friend Joseph Garratt,
in said city,
where he was affectionately and tenderly attended and taken care of during his illness,
we believe in peace with the Lord, and much regretted by Friends here and elsewhere,
amongst whom his zealous labours will be much missed.

We desire that the removal of faithful labourers,
may be so laid to heart by their survivors,
as that they may be incited to copy their examples, tread the same steps to blessedness,
and thereby be qualified to fill their vacant places with propriety.
"`Mark the perfect man, and behold the upright; for the end of that man is peace.`"

He departed this life the 6th of the tenth month, 1780,
and was buried in the burying-ground belonging to Friends of said city,
the 9th of the same.
Aged sixty-seven, a minister forty-one years.

Signed in and on behalf of our Men's meeting held in Dublin,
the tenth of the fourth month, 1781.

John Bancroft, Robert Clibborn, Benjamin Byrne, Henry Astick, Robert Freeman,
Thomas Fayle, Thomas Thack r, Benjamin Glorney, William North, John Smithson,
David Newland, John Robinson, Joshua Forbes, Thomas Bewley, John Dawson Coats,
Joseph Williams, Joshua Clibborn, John Robinson, Jonathan Hill, Joseph Pike,
Joseph Sandwith, William Jackson, William Knott, Thomas Bewley, Jr. Samuel Russel,
Thomas Barrington.
